### ISSUE TITLE
Using INCLUDE with directory paths broken on Windows

### ISSUE THREAD

**Issue by Liniya** [z00m128/sjasmplus#108]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.14.3 and later 	| Windows 7 64-bit 	| INCLUDE	|

A line like this:

```
	INCLUDE "E:\_Programming\spectrum\src\sources\Delay\delay.asm"
```

Gives the following error in versions 1.14.3 and later:

```
SjASMPlus Z80 Cross-Assembler v1.15.0 (https://github.com/z00m128/sjasmplus)
mcolor-test-linear3-30.asm(112): error: Error opening file: E:/_Programming/spec
trum/src/sources/Delay/delay.asm
Для продолжения нажмите любую клавишу . . .
```

It works fine in versions 1.13.0 and prior.

**Comment by ped7g** [comment]
I guess somewhere between the path processing code got forced to fix the slashes in file paths, but as far as I know the correct slashes should work also under windows, i.e. I'm confused why the `fopen("E:/_Programming/spec
trum/src/sources/Delay/delay.asm", "rb")` fails... can you out of curiosity add some `test.asm` files to your drive (around the main file you are assembling) and try also:
```
include "subdir\test.asm"
include "\otherdir\test.asm"
include "c:\otherdir\test.asm" ; replace "c:" with drive where you have main.asm
```
to see if it fails already at simple `subdir/test.asm` or it works until the drive letter ruins it?

Or any chance you can use modern OS instead? :P

The build on windows machines does pass all the tests:
https://cirrus-ci.com/task/4655516632743936

including the "include path" tests using the relative directories. So I'm confused what is failing in your case, as I would expect it to be the same thing as the test for include paths.

**Comment by Liniya** [comment]
Alright, I tried to test it. Firstly, the type of slashes that is used seems to have no effect on it. In both cases, these all work:

```
	INCLUDE "test.asm"
	INCLUDE "subdir\test.asm"
	INCLUDE "\subdir\test.asm"
```

These don't work (same type of error):


```
	INCLUDE "E:\test.asm"
	INCLUDE "E:\subdir\test.asm"
```

So, it's something to do with the drive letter, it seems.


>Or any chance you can use modern OS instead? :P

I tried my best to give Linux a chance this time... I really did. :)

**Comment by ped7g** [comment]
Is the `E` some kind of substitute/network drive? Those may be not completely "transparent" to clib of windows and may require extra win-api specific code to open them correctly I think. I'm not expert on win-api (obviously), so consider this level "rumour".

But if the `e:` is some non-standard fixed drive, try to copy the files to other drive and test that, if it works, you can try to google if it's possible to fix regular `fopen` to open the special drives.

But I'm afraid this may be "won't fix" kind of issue without any solution.

**Comment by Liniya** [comment]
No, it's just a regular HDD partition.

**Comment by ped7g** [comment]
I mean, try simple separate C code `int main() { FILE * f = fopen("e:\...", "rb"); }` using both backslash and forward slash, outside of sjasmplus. sjasmplus in recent versions will always convert backward slashes to forward slashes before calling `fopen`, so if that is the issue, I can maybe do something about it.

But if the `fopen` fails in any case with the drive letter, then I have no idea how to help with this kind of issue.

**Comment by Liniya** [comment]
Works (returns 0):

```
test.asm
\test.asm
subdir\test.asm
subdir/test.asm
\subdir\test.asm
/subdir/test.asm
E:\path\subdir\test.asm
```

Doesn't work (returns 1):

```
/test.asm
E:/path/subdir/test.asm
```

**Comment by Liniya** [comment]
Nevermind my earlier post here. Anyway, these both work (return 1):

```
FILE * f = fopen("E:\\subdir\\test.asm", "rb");
FILE * f = fopen("E:/subdir/test.asm", "rb");
```

**Comment by ped7g** [comment]
wait... so technically everything works ok, except the sjasmplus does not?

Can you hex-view the source with error if the correct file name without some weird invisible chars is within the quotes or something like that?

Because now after your extra test his makes zero sense to me and I really don't know what is failing.

**Comment by Liniya** [comment]
I'm fairly sure everything is OK with these things... As I said, it builds perfectly in 1.13.0 and below.

**Comment by ped7g** [comment]
can you attach some small example of asm + lst file to this ticket, so I can check the files in binary way if there is anything odd about them, or how the sjasmplus does modify the path to fix slashes? Maybe the sjasmplus does damage the string and fopen then must fail. But I need the same file as you have to be sure I'm debugging the same thing.

**Comment by Liniya** [comment]
Here: [test-include.zip](https://github.com/z00m128/sjasmplus/files/4766303/test-include.zip). Unpack to the root of any drive and compile `test-include.asm`. It's set to use `E` at the moment, you can probably change that if you want. I'm not including a `lst` because it doesn't actually create one when it gives this error.

By the way, I found something quite strange. If sjasmplus is invoked like this:

`E:\_Programming\spectrum\cli\sjasmplus\new-stable\sjasmplus.exe test-include.asm`

Then the test files compile with no error! However, when invoked like this:

`E:\_Programming\spectrum\cli\sjasmplus\new-stable\sjasmplus.exe E:\test-include.asm`

Then it complains about missing `test.asm` again (NOT `test-include.asm`).
This is also the case with the file `mcolor-test-linear3-30.asm` mentioned in the OP.

**Comment by ped7g** [comment]
Works for me in linux... (I did create symbolic link `E:` in current directory linked to current directory with `ln -s ./ E\:` and the listing looks like this:
```
# file opened: test-include.asm
1     0000              	DEVICE ZXSPECTRUM48
2     0000
3     0000              	ORG #8000
4     8000
5     8000              	INCLUDE "E:\test.asm"
# file opened: E:/test.asm
1+    8000 7F           	ld a,a
2+    8001
# file closed: E:/test.asm
6     8001              	INCLUDE "E:\subdir\test.asm"
# file opened: E:/subdir/test.asm
1+    8001 7F           	ld a,a
2+    8002
# file closed: E:/subdir/test.asm
7     8002
# file closed: test-include.asm
```
i.e. the slashes are converted and `fopen` works without any issue.

So again the main suspect is back on the windows themselves, I have no idea why `fopen` works in your own C code, but does not in sjasmplus, with the same string as argument.

Maybe the crtlib linked to sjasmplus is worse than the one you are using... what compiler/version did you use to test your C code, and what exe are you using for sjasmplus, the official release one or custom build from sources with some local compiler and which version?

I will also try to get somebody with windows and C++ experience to try the same thing on their system, maybe somebody will have the same issue and can debug it, what is happening and why, because right now I have no idea what is wrong. (there are too many changes between 1.13.0 and 1.14.3, that's 328 commits... if are bored, you can try to download all versions between a bisect it until you find the last working vs first failing)

**Comment by ped7g** [comment]
the only other suspicion I have is the full-filename string builder, maybe I have some bug there and it works by luck on linux because the new memory is cleared from kernel more often than in windows and the name is somehow damaged, but I did take a quick look on the code and also at your OP report, and I don't see anything like that except you have newline character in the error message, but I guess that was added by you while posting the message, and not by assembler (or it is done by terminal because of narrow window?)

BTW you can produce listing file even with fatal error by:
`sjasmplus --msg=lstlab file.asm 2> file.lst`

I'm currently at end of my wits, but I will keep this open and try to get somebody with windows to try and debug it (i.e. I believe you have the error, I just don't understand where it comes from, sorry)

**Comment by Liniya** [comment]
C compiler: `gcc version 8.1.0 (i686-win32-sjlj-rev0, Built by MinGW-W64 project)`

As for sjasmplus, I'm just using stable versions from releases provided here. I don't have all of the required tools set up on this machine yet, so I cannot compile it from the sources at the moment.

>there are too many changes between 1.13.0 and 1.14.3, that's 328 commits...

I think I might have narrowed it down further now. It's between 1.13.2 (still works for me) and 1.13.3 (doesn't).

**Comment by Liniya** [comment]
[file-1.13.3.lst.txt](https://github.com/z00m128/sjasmplus/files/4766593/file-1.13.3.lst.txt)
[file-1.15.0.lst.txt](https://github.com/z00m128/sjasmplus/files/4766594/file-1.15.0.lst.txt)

**Comment by ped7g** [comment]
Wait, the 1.13.3 is even using backslashes. And it still fails. So conversion of slashes didn't start this. I need to ask z00m if he can remember how he did build the official exe files, if there was some change of compiler.

Thank you for the detailed info so far.

**Comment by ped7g** [comment]
when you start it like `sjasmplus e:\file.asm`, the `e:\` becomes one of the include paths in a way it was not supposed to, confusing `include` later to try wrong filenames like `e:\e:/test.asm`

So I finally understand what is happening on the `fopen` side, it's bug in sjasmplus and should be fixed for next release (I don't yet fully understand why current code is producing wrong filenames, but I have now enough debug data to investigate further).
