### ISSUE TITLE
LUA sj.add_byte causes target out of range error

### ISSUE THREAD

**Issue by Truevideo** [z00m128/sjasmplus#113]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.15.0 	| Windows 10 1903	| LUA sj.add_byte	|

I'm trying to initialize an area of memory with sj.add_byte. Below is a very stripped-down version of what I'm trying to accomplish:

```
		DEVICE ZXSPECTRUM128

		ORG	#8000

		LUA
		for i=0,255 do
			sj.add_byte(0)
		end
		ENDLUA

		DISPLAY $
		JR	JUMP 
JUMP
```

This outputs the following messages on the console:

> 0x8100
Test.s(14): error: [JR] Target out of range (-256)
Error

So even though the current assembly address ($) is holding the expected value (0x8100) it looks like the offset for the relative jump is not properly computed.

Is sj.add_byte the right way to generate custom blocks of data on the fly with LUA?

Thanks

**Comment by ped7g** [comment]
Yeah, it's tricky... you did almost everything correctly, except that `LUA` by default means `LUA PASS3`, creating the block only in last pass, so your `JUMP` label is during pass1 and pass2 equal 0x8000 (because there is no table generated), and then in pass3 you add new 0x100 bytes, affecting positions of all labels, but the `JR JUMP` will use label value from pass2, and the discrepancy happens.

If lua block is emitting some machine code bytes, it should emit them in every pass (the same amount of them, values don't matter too much, often final values can be done in pass3 only, but the amount of machine code is critical, that should be equal for all passes, or at least for pass2 and pass3). I.e. your code should be:
```
		ORG	#8000

		LUA ALLPASS   ; "allpass" modifier to create the same table in every pass
		for i=0,255 do
			sj.add_byte(0)
		end
		ENDLUA
```

Thanks to your report I did find the `tests/lua_examples/lua_sin_table.asm` was actually showing the same issue, but as "example", so I fixed that example (I guess you may have seen it there, the add_byte usage?).

IIRC the docs mention the importance of `allpass` for machine code generators, but I guess it's easy to overlook and also it may be not obvious how the assembler actually works and why same machine code is needed in every pass for correct results, so having good examples is also important. Thanks for reporting this, and I hope this answer does resolve your issue. :)

**Comment by ped7g** [comment]
Actually the assembler should probably emit warning about this.... HMMMmmm....

**Comment by Truevideo** [comment]
Yes, I totally overlooked the ALLPASS modifier. Thanks for the heads up
