### ISSUE TITLE
SAVESNA automatically disables interrupts

### ISSUE THREAD

**Issue by flatduckrecords** [z00m128/sjasmplus#139]
| Version 	| Platform 		| Topic 	|
|---------	|--------------	|-------	|
| v1.18.2		| macOS 11.2.3	| interrupts	|

When a SNA file is created with the SAVESNA pseudo-op, interrupts are disabled by default. The raw assembled output behaves as expected, so it appears to be an issue with the SNA container file?

```
	DEVICE ZXSPECTRUM48

	org 32768
	;ei			; without enabling interrupts here, the Spectrum will
	halt			; hang at the next halt instruction.
	ret

	SAVESNA "test.sna", 32768
```

**Comment by ped7g** [comment]
yes, the `savesna` does produce IM1 + `di` status in the header (this is intentional default and not going to change, as it is "safest" for most of the use-cases).

You can set up interrupts (including `ei`) as you need them in the code after it is executed.

I'm looking at the SAVESNA code, and considering whether to add more arguments to `SAVESNA` to make more of the header configurable, but no promises.

If you want different SNA header, you can post-patch the final file header afterwards with current sjasmplus for example like this:

```
    ; ....
    SAVESNA "file.sna",start  ; some file.sna produced
    IF 3 == __PASS__
        DEVICE NONE : ORG 0
        OUTPUT "file.sna",r
        FPOS $00 : DB $FE       ; I = $FE (IM2 table starts at $FE00)
        FPOS $13 : DB (1<<2)    ; (bit 2) IFF2 = 1 -> "enable interrupts"
        FPOS $19 : DB 2         ; IM2 mode
        FPOS $1A : DB 2         ; border = 2
        OUTEND
    ENDIF
```
For header structure check this: https://sinclair.wiki.zxnet.co.uk/wiki/SNA_format

**Comment by flatduckrecords** [comment]
Thanks Peter, yes I understand. Thanks for taking the time to respond, I believe the patch code you suggested will suit my needs. Cheers!
