### ISSUE TITLE
[Docs] macro arguments question

### ISSUE THREAD

**Issue by ammehet** [z00m128/sjasmplus#141]
There are examples of macros in the documentation. Some of them have question mark as argument's postfix
```
LabelAsMacroName    MACRO  arg1?, arg2?
                        ld  a,arg1?
                        ld  hl,arg2?
                    ENDM
```
some haven't
```
    MACRO UseLess data
      DB data
    ENDM
```
Does it have any special meaning or it's just decoration to eliminate possible naming conflicts?

**Comment by ped7g** [comment]
> Does it have any special meaning or it's just decoration to eliminate possible naming conflicts?

The latter... the macro arguments use the same string-substitution system like `DEFINE`, which is overly aggressive, so for example:
```
  MACRO argtest x
.label_x:  ld a,x
  ; ^ the substitution system will replace also the "x" in "label_x"
  ENDM

  argtest (1+2)
  ; ^ fails on assembling line: .label_(1+2): ld a,(1+2)
```

Question marks are valid identifier/label character in sjasmplus, but very unlikely to be used by many users, so peppering macro arguments with them solves accidental substitution mid-word match, and to me personally they look visually pleasing, as in "it's visually marking what is macro argument".

Because of the other accidental damage produced by that aggressive substitution, I'm considering adding global switch to disable mid-word substitution in v1.18.3 (#140)

**Comment by ammehet** [comment]
Thanks for the detailed explanation!

**Comment by specke** [comment]
ped7g, I hope just a switch, because this substitution mechanism is absolutely invaluable!

**Comment by ped7g** [comment]
switch 100%, 95% by default ENABLED, at least for v1.x

If I ever do v2.x, I guess I will flip the substitution to follow the original idea of patch author (it was originally meant to sub-string substitute only with defines starting with underscore like `define _x ...`, not starting with letters like `define x ...`, but the bug in original author patch lead to flaky behaviour and the wrong interpretation was enforced by old test, which was using the bug-way to verify the functionality), and make it still default, because it's handy feature, when it works as you expect.

The current sjasmplus behaviour is somewhat annoying and surprising (in the wrong way), but it is, what it is, I don't have "balls" to change it now for v1.x (also I find the current v1.18.x being quite "solid", most of the enhancements left are rather intrusive or require serious internal rewrite, almost all low handing fruit is now done, so it's kinda end-of-chapter and I would find it a bit strange to change syntax rules here).

The new switch will be mostly for migrating legacy projects from other assemblers with less pain (or for people who really hate the current feature).
