### ISSUE TITLE
Full-fledged temporary labels

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#168]
it's impossible to code without

```
dup 100500
2
ld a,(1_f) ;or 1f of f1 of f_1 etc
1 = $+2
ld hl,2_b
edup
```

**Comment by ped7g** [comment]
yes, temporary labels are only for jumps.
if you need them this badly, use them with jump:
```
  DEVICE NOSLOT64K ; have virtual device memory so machine code can be patched
  ORG $2000
  DUP 4
2:
  jp 1f : org $-3 : ld a,({$+1}+2)  ; ld a,(1f+2)
1: ; also can't do equ/defl, so "+2" moved above into ld
  jp 2b : org $-3 : ld hl,{$+1} ; ld hl,2b
  EDUP
  SAVEBIN "test.bin", $2000, $-$2000
```
after assembling:
```
$ hd test.bin 
00000000  3a 05 20 21 00 20 3a 0b  20 21 06 20 3a 11 20 21  |:. !. :. !. :. !|
00000010  0c 20 3a 17 20 21 12 20                           |. :. !. |
```
so that's like:
```
  ORG $2000
  ld a,($2005) ; at $2000
  ld hl,$2000
  ld a,($200B) ; at $2006
  ld hl,$2006
  ld a,($2011) ; at $200C
  ld hl,$200C
  ld a,($2017) ; at $20012
  ld hl,$2012
```
But I would personally write rather some lua or C code generator producing regular labels for this, to make it more readable.

to add temporary labels for regular instructions, I don't know how to deal with this:
```
101:
  ld hl,101b  ; is this ld hl,5 or ld hl, temporary_label, and how do you decide?
```
If the binary suffix "b" would be removed from sjasmplus syntax, then there would be no clash. It wouldn't be probably fun to implement, but at least the syntax wouldn't be broken, like it is now. (`jp 101b` is now temporary label even if it does not exist, so if you want `jp 5`, you have to avoid binary suffix form, either using decimal/hexa `5` or percent sign `jp %101`).

**Comment by NEO-SPECTRUMAN** [comment]
>It wouldn't be probably fun to implement

1_backward
1_forward

**Comment by ped7g** [comment]
the `_f` and `_b` is maybe reasonable... as long as digit delimiter group will stay `'` forever and `_` support will be not added, but even then `b` is not valid digit, so `_b` would hold.

This is probably doable, can't see how it would clash with old syntax or projects.

**Comment by mbaze** [comment]
Couldn't something like this solve your problem?
```
          macro TEST_MACRO
.start    ld a,(.label + 2)
.label    ld hl,.start
          endm

          org #8000
          rept 10
          TEST_MACRO
          endr
```

**Comment by NEO-SPECTRUMAN** [comment]
nope
lua to
