### ISSUE TITLE
Unnecessary compilation stop due to the opening file error

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#170]
`xxxx.asm(12): error: Error opening file: xxx2.asm`

compiler is trying to build the code despite everything...
...except opening file errors...
and when you try to throw out a lot of includes
it is pain...
...
especially when code is still fully functional...

**Comment by ped7g** [comment]
I personally disagree about this.
I will keep this open and active sjasmplus users can voice their preference (comment, or emoji your or mine comment) and we will see, but missing file could cause many errors further down in the code, and it will be just more difficult to find what failed. Also I'm a bit confused what's the issue, you just hit F4 or what is in your IDE to navigate to first error, fix/delete the include, hit build ... next ... should be couple of minutes job even if you have like 20-30 files missing.

I know, because sometimes I'm trying to assemble open source projects from windows users, who have wrong file names, so it fails on case sensitive file system, so I have to fix all include names to correct spelling to just build it.

**Comment by NEO-SPECTRUMAN** [comment]
> I personally disagree about this.

errors must be
not stop compilation

**Comment by NEO-SPECTRUMAN** [comment]
>but missing file could cause
NOW sjasm compliling jp to MISSING LABEL as JP $0000

>in your IDE

my IDE?

**Comment by ped7g** [comment]
npp is notepad++? That [should be possible to configure](https://stackoverflow.com/questions/13931641/can-notepad-be-configured-to-recognize-compiler-error-messages-and-jump-to-the) to run assembling and parse output for errors too, like most of the text editors. (I use Kate, which has now also windows version available, but I guess you would not want to switch just for Z80 asm projects.. :D ... but if you ever would consider that, you would get also syntax highlight for sjasmplus dialect and I can help you to configure it :) )

**Comment by ped7g** [comment]
@Volutar that's fresh idea to me.

Most of the assembling errors are emitted during last pass (currently third), include-errors are in first pass.

With your idea implemented trivially (continue with assembling, but stop after first pass) you would collect all the include errors, but nothing about code syntax, etc...

That sounds interesting.

**Comment by NEO-SPECTRUMAN** [comment]
>That sounds interesting.
it's still unnwcessary stop compilation

**Comment by NEO-SPECTRUMAN** [comment]
also the SAME SHIT!
"error: file too short:"
its must be error/warning
NOT STOP COMPILATION
