### ISSUE TITLE
"Bytes lost"

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#18]
Hi,

I had problems assembling some of my programs. I could drill it down to the following
problematic lines:
` ORG	32769

CHR:	DEFW	0,0,0,0

HINA:	LD	DE,-CHR
	ADD	HL,DE`

sjasmplus gives the error:
`SjASMPlus Z80 Cross-Assembler v1.10.3 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
test.asm(5): error: Bytes lost
Pass 2 complete (1 errors)
test.asm(5): error: Bytes lost
Pass 3 complete
Errors: 2, warnings: 0, compiled: 7 lines, work time: 0.001 seconds`

Note: if ORG is chosen lower or equal 32768 it assembles without a problem.

**Comment by z00m128** [comment]
In SjASMPlus all labels are internally interpreted as 32-bit values, and sometimes the operations intended as 16-bit could end up in result, which is more than 16-bits wide (as in your case). Then you get `Bytes lost` error. We agree it is not very clear and it should be handled as warning only, because the code is compiled correctly. As a workaround to avoid these type of warnings, you can use `and 65535` operation to be sure the result will not exceed 16 bits (`LD DE,-CHR and 65535`).

**Comment by maziac** [comment]
I thought that it is something like this but was not sure.
Not a big deal to workaround this.

**Comment by z00m128** [comment]
_"Bytes lost"_ warning messages reworked by Busy in https://github.com/z00m128/sjasmplus/commit/5c2fc5a092c73044079c6cc8f586adc049e6b335
