### ISSUE TITLE
saving in doesn't existing folder causing unnecesary fatal error instead of creating new folder

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#202]

**Comment by ped7g** [comment]
This is by design, common behaviour of gcc, clang, lua and plenty other compilers, assemblers and script languages.

You can maybe try `SHELLEXEC mkdir -p path` to create it in third pass (as all SAVE directives will try to open files in third pass), but it will still fail for some other output files like --raw/--exp/... which open file probably during initialisation of third pass, before the `SHELLEXEC` will be reached.

In such case just fix your build script to create output folder before assembling :man_shrugging:
