### ISSUE TITLE
Allow multiple labels as arguments of IFUSED

### ISSUE THREAD

**Issue by specke** [z00m128/sjasmplus#206]
IFUSED provides a convenient way of defining libraries of functions that are added to the program only when they get used somewhere in the code. Unfortunately, if a function has multiple points of entry / patterns of use, the mechanism of IFUSED becomes insufficient. For example
```
	IFUSED UsefulRoutine
UsefulRoutine:	ld b,0
.UseValueInB	djnz $
		ret
	ENDIF
```
would work if you need to `call UsefulRoutine`, but would not if you `ld b, 10 : call UsefulRoutine.UseValueInB`.

An ideal way to solve it would be to treat `IFUSED UsefulRoutine` in an extended sense, i.e. to say that `IFUSED UsefulRoutine` gets included as long as ANY label from this part of the namespace is used. I.e. the use of `UsefulRoutine.UseValueInB` should be sufficient. But this behaviour may be code-breaking, so I can see why this may not be the way to move forward.

Alternatively, some form of expression-like syntax could be accepted as an argument of IFUSED. I.e. my example above could be solved by allowing `IFUSED UsefulRoutine | UsefulRoutine.UseValueInB`, which means include code if the outside code uses one label or the other.

**Comment by ped7g** [comment]
I like the idea of main label covering also all local labels in `IFUSED`, would need to think more about backward compatibility and if it would break something... It should not break projects which use main and local labels in verbose rich-name way, as the `call UsefulRoutine.UseValueInB` is very like trying to reach for main+local label in such project, while people using cryptic labels with dots as regular char could maybe hit some collision, but then it will also fail to assemble because of duplicate label... so this extension would be rather safe-ish IMHO.

Expression way is unlikely, if something like that happens, it will be rather just coma separated list: `IFUSED UsefulRoutine, UsefulRoutine.UseValueInB` ... I sometimes hit in my own projects situations where I would prefer to have ISUSED/ISDEF as expression operators, but I'm afraid to add too many new ones in v1.x, while adding the optional var-args for IFUSED is perfectly backward compatible, only limits any future extension by using this syntax for this purpose (unlikely to be an issue I guess).

**Comment by ped7g** [comment]
Meanwhile I realized there is one more work-around for this (which is IMHO decent), if you know you want local label of some `IFUSED` routine, you can ASSERT the main label to make it used and routine included, then the local label is found:
```
 ORG $8000
some:
 IFUSED
  ld b,123
.loop:
  djnz .loop
  ret
 ENDIF

 ld b,222
 ASSERT some
 call some.loop
```

**Comment by specke** [comment]
Haha, just tried it in my code and it works great. This is what I like about sjasmplus - how rich its command set is, so even the missing features can often be imitated.
