### ISSUE TITLE
Arrow keys and ESC don't work after invoking sjasmplus

### ISSUE THREAD

**Issue by chupocro** [z00m128/sjasmplus#216]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.20.3 	| Windows 10 22H2 | Invoking	|

After invoking the latest version of `sjasmplus` from `cmd` the arrow keys don't work in the terminal anymore and it is not possible to recall the last command nor navigate the cursor within the line. Instead of `Up arrow` there is `^[[A`, instead of `Left arrow` there is `^[[D` etc. and there is `^[` instead of `ESC`.

Version `1.15.0` which I was using until now works well.

Another change since version `1.15.0` is the output produced by `DISPLAY` directives is now teal `RGB(0x00, 0x80, 0x80)`, maybe there is a problem with terminal color codes but the same happens even when there isn't a `DISPLAY` directive.

**Comment by ped7g** [comment]
can you try `sjasmplus --color=off` to get DISPLAY without color codes, if that helps with arrows, but I don't expect the main issue to be related to ANSI color codes, so I expect the color off to not help. Would be nice if you can confirm it, as I don't have any windows machine to try myself.

**Comment by ped7g** [comment]
oh, looking into the code, that will turn colors off, but still tamper with console settings, so if you can try also other experiment with setting environment `NO_COLOR` (to any value, just have to exist) before running sjasmplus, and then see if that does affect behaviour. Thank you.

**Comment by chupocro** [comment]
Hi again :-) Setting the environemnt variable `set NO_COLOR=1` solved the problem while the switch `--color=off`, as you expected, didn't.

**Comment by ped7g** [comment]
so the issue is this code (which is used to enable ANSI color codes in windows cmd.exe):
https://github.com/z00m128/sjasmplus/blob/master/sjasm/support.cpp#L147-L149

issue is known and "by design":
https://github.com/microsoft/terminal/issues/4949

so the remaining question is whether I want to care and try to un-set the virtual input processing before existing sjasmplus (shouldn't be too hard in case of clean exit, in case of fatal error it may require extra call in code to cleanup in such case too), or I will tag this as wont-fix and suggest to use more modern OS like some linux.

**Comment by ped7g** [comment]
I did try to add console mode restoration in windows upon sjasmplus exit. As I have no means to test what this change does, it may fix things or it may make them worse...

If you can build the master branch yourself and verify the fix works (and the ANSI colors still work, ie. `DISPLAY` is teal), I will be thankful, otherwise this will go out untested with next release, which I have right now no plans to do any time soon.

With current sjasmplus release you can also use `NO_COLOR` environment variable, although I would once more suggest to switch OS, as MS windows will very likely become more and more tedious to support over time.
