### ISSUE TITLE
merging labels

### ISSUE THREAD

**Issue by DeadlyKom** [z00m128/sjasmplus#234]
there are two shorter label declarations with the same main declaration in different files

first
![image](https://github.com/user-attachments/assets/e5a712b4-a6cf-4cc6-8ed6-58210f484777)

second
![image](https://github.com/user-attachments/assets/0b6f0493-af2f-445c-bf0c-3208586d62a1)

It would be nice if sjasmplus would combine them, and I could access them freely, without duplication errors

**Comment by ped7g** [comment]
You can achieve the desired result by using `MODULE`, either in both cases, or you can even "abuse" it to extend namespace defined by main label earlier:

```
; a bit dirty way (module was not meant to be used like this), but works:
Collision:       ; defines Collision symbol
.Prepare        EQU 123  ; defines Collision.Prepare symbol
.Handler        EQU 234 ; defines Collision.Handler symbol

 ... other file ...

        MODULE Collision
Initialize      EQU 345  ; defines Collision.Initialize symbol
        ENDMODULE
```

or using `Collision` only as module (not as main symbol):
```
        MODULE Collision
Prepare         EQU 123
Handler         EQU 234
        ENDMODULE

 ... other file ...

        MODULE Collision
Initialize      EQU 345  ; defines Collision.Initialize symbol
        ENDMODULE
```

Doing second time `Collision:` is duplicate label and I don't see how to enable your proposal without causing havoc with accidental errors of adding duplicate labels by accident. Those should be reported as errors, as they are now.

I hope this helps.

**Comment by DeadlyKom** [comment]
печально!

**Comment by ped7g** [comment]
Sorry, but I don't share your sentiment. As far as I can tell the `module` enables you to do exactly what you want, yet it doesn't break regular assembler functionality, so it's like win-win situation IMHO?

I understand it's different syntax, so the source will looks slightly different, but otherwise it's almost 1:1 what you asked for.

If you have issues to use sjasmplus in your project, you can always try to post some example project with the problem, or email me full project privately (see email in commits in git or check file asm-z80-sj.xml ). Happy coding! :)
