### ISSUE TITLE
Next tile maps: default slot behaviour despite MMU.

### ISSUE THREAD

**Issue by OnceBitten** [z00m128/sjasmplus#245]
The code:

```
  OPT --syntax=abfw --zxnext
;-------------------------------------------------------------------------------

  DEVICE ZXSPECTRUMNEXT ; ZX Spectrum Next (8 slots, 224 8KiBanks="pages" in sjasm-speak, slot size 0x2000 = 1.75MiB RAM)
                        ; default banks map: [ 14,  15,  10,  11,  4,  5,            0,                1] = [7, 5, 2, 0] in 16KiB terms, like ZXSPECTRUM128
                        ; nexload banks map: [255, 255,  10,  11,  4,  5, 2*entry_bank, 2*entry_bank + 1]
                        ; default slot = 7 = $E000 - $FFFF
  LABELSLIST "experiment.lbl"

  MODULE Next

TRANSPARENCY_COLOUR_FALLBACK                  EQU $4A
MEMORY_MANAGEMENT_SLOT_0_BANK                 EQU $50
MEMORY_MANAGEMENT_SLOT_1_BANK                 EQU $51
MEMORY_MANAGEMENT_SLOT_2_BANK                 EQU $52
MEMORY_MANAGEMENT_SLOT_3_BANK                 EQU $53
MEMORY_MANAGEMENT_SLOT_4_BANK                 EQU $54
MEMORY_MANAGEMENT_SLOT_5_BANK                 EQU $55
MEMORY_MANAGEMENT_SLOT_6_BANK                 EQU $56
MEMORY_MANAGEMENT_SLOT_7_BANK                 EQU $57
ULA_CONTROL                                   EQU $68
TILEMAP_CONTROL                               EQU $6B
DEFAULT_TILEMAP_ATTRIBUTE                     EQU $6C
TILEMAP_BASE_ADDRESS                          EQU $6E ; As msB of offset in 16KiB-bank 5: tilemap data is always in this bank.
TILE_DEFINITIONS_BASE_ADDRESS                 EQU $6F ; As msB of offset in 16KiB-bank 5.

SLOT_SIZE                                     EQU $2000
SLOT_0_START                                  EQU $0000
SLOT_0_END                                    EQU SLOT_0_START + SLOT_SIZE - 1 ; $1FFF
SLOT_1_START                                  EQU SLOT_0_END + 1               ; $2000
SLOT_1_END                                    EQU SLOT_1_START + SLOT_SIZE - 1 ; $3FFF
SLOT_2_START                                  EQU SLOT_1_END + 1               ; $4000
SLOT_2_END                                    EQU SLOT_2_START + SLOT_SIZE - 1 ; $5FFF
SLOT_3_START                                  EQU SLOT_2_END + 1               ; $6000
SLOT_3_END                                    EQU SLOT_3_START + SLOT_SIZE - 1 ; $7FFF
SLOT_4_START                                  EQU SLOT_3_END + 1               ; $8000
SLOT_4_END                                    EQU SLOT_4_START + SLOT_SIZE - 1 ; $9FFF
SLOT_5_START                                  EQU SLOT_4_END + 1               ; $A000
SLOT_5_END                                    EQU SLOT_5_START + SLOT_SIZE - 1 ; $BFFF
SLOT_6_START                                  EQU SLOT_5_END + 1               ; $C000
SLOT_6_END                                    EQU SLOT_6_START + SLOT_SIZE - 1 ; $DFFF
SLOT_7_START                                  EQU SLOT_6_END + 1               ; $E000
SLOT_7_END                                    EQU SLOT_7_START + SLOT_SIZE - 1 ; $FFFF
NEX_ENTRY_BANK_SLOT                           EQU 6
NEX_ENTRY_BANK_SLOT_START                     EQU SLOT_6_START

HIGHEST_UNEXPANDED_BANK_16K                   EQU 47
HIGHEST_EXPANDED_BANK_16K                     EQU 111
HIGHEST_UNEXPANDED_BANK_8K                    EQU 2*HIGHEST_UNEXPANDED_BANK_16K + 1
HIGHEST_EXPANDED_BANK_8K                      EQU 2*HIGHEST_EXPANDED_BANK_16K   + 1

TILEMAP_16K_BANK                              EQU 5     ; Tilemap data is always in 16KiB-bank 5 when not "shadowing" to 16KiB-bank 7.
TILEMAP_8K_BANK                               EQU 2*TILEMAP_16K_BANK

TILEMAP_LOWEST_MAP_OFFSET                     EQU $2000 ; Must be 256b-aligned, due to TILEMAP_BASE_ADDRESS set to msB only.
                                                        ; Lowest without stomping sysvars, according to Dev Guide.
TILEMAP_40X32X1_LOWEST_DEFINITIONS_OFFSET     EQU $2500 ; Must be 256b-aligned, due to TILEMAP_DEFINITIONS_BASE_ADDRESS set to msB only.
                                                        ; Lowest for 40x32x1B tilemap.
TILEMAP_40X32X2_LOWEST_DEFINITIONS_OFFSET     EQU $2A00 ; Must be 256b-aligned, due to TILEMAP_DEFINITIONS_BASE_ADDRESS set to msB only.
                                                        ; Lowest for 40x32x2B tilemap.
TILEMAP_80X32X1_LOWEST_DEFINITIONS_OFFSET     EQU $2A00 ; Must be 256b-aligned, due to TILEMAP_DEFINITIONS_BASE_ADDRESS set to msB only.
                                                        ; Lowest for 80x32x1B tilemap.
TILEMAP_80X32X2_LOWEST_DEFINITIONS_OFFSET     EQU $3400 ; Must be 256b-aligned, due to TILEMAP_DEFINITIONS_BASE_ADDRESS set to msB only.
                                                        ; Lowest for 80x32x1B tilemap.
  ENDMODULE ; Next

MY_NEX_STACK_POINTER              EQU Next.SLOT_0_START ; PUSH'ed word is written below ex-ante SP, so $0000 gives $FFFF as top of stack data
MY_ENTRY_BANK_16K                 EQU Next.HIGHEST_EXPANDED_BANK_16K
MY_ENTRY_BANK_8K                  EQU 2*MY_ENTRY_BANK_16K
MY_TILEMAP_SLOT                   EQU 7
MY_TILEMAP_SLOT_START             EQU Next.SLOT_7_START
MY_TRANSPARENCY_COLOUR_FALLBACK_1 EQU $FF
MY_TRANSPARENCY_COLOUR_FALLBACK_2 EQU $00

;-------------------------------------------------------------------------------
; Code
;-------------------------------------------------------------------------------

  MMU Next.NEX_ENTRY_BANK_SLOT e, MY_ENTRY_BANK_8K ; nex entry bank mapped to slot 6 (and 7 as it is a 16KiB bank)
  ORG Next.NEX_ENTRY_BANK_SLOT_START               ; $C000

entry:
  call initialise_screens
  ld B, $FF
1:
  ld A, B
  nextreg Next.TRANSPARENCY_COLOUR_FALLBACK, A
  dec B
  jp 1_B

initialise_screens:
  nextreg Next.TRANSPARENCY_COLOUR_FALLBACK, MY_TRANSPARENCY_COLOUR_FALLBACK_1
  nextreg Next.ULA_CONTROL,              %1'01'1'0'0'0'0  ; disable ULA output, no ULA/Tilemap blending, disable ULA+ and ULA half-pixel scroll, disable stencil mode
                                                          ; cancel entries in 8x5 matrix for extended keys
  nextreg Next.TILEMAP_CONTROL,          %0'0'0'0'0'0'0'0 ; disable Tilemap
                                                          ; 40x32 mode
                                                          ; use attribute byte
                                                          ; first Tilemap palette
                                                          ; disable 1-bit Tilemap
                                                          ; 256 tile mode
                                                          ; Tilemap below ULA
  nextreg Next.TILEMAP_BASE_ADDRESS, tilemap_offset
  nextreg Next.TILE_DEFINITIONS_BASE_ADDRESS, tile_definitions_offset
  nextreg Next.TILEMAP_CONTROL,          %1'0'0'0'0'0'0'0 ; enable Tilemap
                                                          ; 40x32 mode
                                                          ; use attribute byte
                                                          ; first Tilemap palette
                                                          ; disable 1-bit Tilemap
                                                          ; 256 tile mode
                                                          ; Tilemap below ULA
  ret

;-------------------------------------------------------------------------------
; Tilemap data
;-------------------------------------------------------------------------------

  MMU MY_TILEMAP_SLOT e, Next.TILEMAP_8K_BANK
  ORG MY_TILEMAP_SLOT_START + Next.TILEMAP_LOWEST_MAP_OFFSET

tilemap_offset          EQU high (tilemap - MY_TILEMAP_SLOT_START)
tile_definitions_offset EQU high (tile_definitions - MY_TILEMAP_SLOT_START)

tilemap:
  DUP 32
    DUP 20
      db 0, ($F<<4) or %0000'0'0'0'0 ; palette offset $F, no mirroring or rotation, ULA mode irrelevant as disabled.
      db 1, ($F<<4) or %0000'0'0'0'0
    EDUP
  EDUP

  ORG MY_TILEMAP_SLOT_START + Next.TILEMAP_40X32X2_LOWEST_DEFINITIONS_OFFSET 

T0C EQU $33
T1C EQU $AA

tile_definitions:
tile0:
  db T0C, $ff, $ff, T0C
  db T0C, $ff, $ff, T0C
  db T0C, $ff, $ff, T0C
  db T0C, T0C, T0C, T0C
  db T0C, T0C, T0C, T0C
  db T0C, $ff, $ff, T0C
  db T0C, $ff, $ff, T0C
  db T0C, $ff, $ff, T0C
tile1:
  db T1C, T1C, T1C, T1C
  db T1C, $ff, $ff, T1C
  db T1C, $ff, $ff, T1C
  db T1C, $ff, $ff, T1C
  db T1C, $ff, $ff, T1C
  db T1C, $ff, $ff, T1C
  db T1C, $ff, $ff, T1C
  db T1C, T1C, T1C, T1C

;-------------------------------------------------------------------------------
;  SAVENEX pseudo-ops
;-------------------------------------------------------------------------------

  SAVENEX OPEN  "experiment.nex", entry, MY_NEX_STACK_POINTER, MY_ENTRY_BANK_16K, 2 ; strictly nex file standard V1.2.
  SAVENEX CORE  3, 1, 5    ; 3.1.5 for extended keys.
  SAVENEX CFG   5, 1, 0, 1 ; cyan border, file handle in BC, default NextRegs, 2MiB required.
  SAVENEX AUTO
  SAVENEX CLOSE  
```

produces the following behaviours in CSpect, when the lines 70 and 71 are changed so that MY_TILEMAP_SLOT and MY_TILEMAP_SLOT_START vary from 0 to 7 and $0000 to $E000 commensurately.

```
--------------------------------------------------------------------------------------------
MY_TILEMAP_SLOT             0        1        2        3        4        5        6        7
--------------------------------------------------------------------------------------------
behaviour                  B1       B2       B3       B1       B1       B4       B1
tilemap:lst              2000     4000     6000     8000     A000     C000     E000
tilemap:lbl           15:0000  10:0000  11:0000  04:0000  05:0000 222:0000  01:0000
tile_definitions:lst     2A00     4A00     6A00     8A00     AA00     CA00     EA00
tile_definitions:lbl  15:0A00  10:0A00  11:0A00  04:0A00  05:0A00 222:0A00  01:0A00
--------------------------------------------------------------------------------------------
sjasmplus default "maps"   14       15       10       11        4        5        0        1 (8KiB-banks) 
nexload default maps      255      255       10       11        4        5      222      223 (8KiB-banks, 222 is specified here as entry bank)
--------------------------------------------------------------------------------------------
```
where:
  B1 = moving multicoloured bands in border, ULA-size orange pixel area.
  B2 = fully black screen.
  B3 = fully working behaviour - tiles present, showing multicoloured bands through their transparent areas.
  B4 = Greenish cyan border, ULA-size white pixel area.

MY_TILEMAP_SLOT EQU 7 is not tabulated as it produces the following assembly error:
experiment.asm(118): error: value 0x10000 is truncated to 16bit value: 0x0000
experiment.asm(131): error: value 0x10A00 is truncated to 16bit value: 0x0A00 
Which is quite understandable as an ORG to an address greater than $FFFF is attempted in this case.

The reveals several "issues", _which may well be either wholly or in part mere issues with my understanding_:

  1) No warning from the MMU 'e' option occurs when ORG'ing out of MY_TILEMAP_SLOT, i.e. with offsets $2000 and $2A00. Even if the tilemap is brought forward 256 bytes, no warning occurs when assembling through the $1FFF-$2000 slot boundary.

  2) The table evidences that sjasmplus uses its "default bank" (= implicit MMUis, I believe, see Q2 below) associated with MY_TILEMAP_SLOT, despite the presence at line 117 of an MMU pseudo-op associating (emulative "mapping") MY_TILEMAP_SLOT to 8KiB-bank Next.TILEMAP_8K_BANK (EQU 10).

Unfortunately this issue intersects with that of locating a tilemap, of which I am not 100% confident in my knowledge. My understanding of tilemaps in respect of memory is as follows:

  a) The starts of both tile map and tile defintions are aligned 256.

  b) They must both occur in same 16KiB-bank as the ULA Layer, thus 16KiB-bank 5 or 7 according as "shadowing" bit 3 of 'Memory Paging Control' port $7FFD is reset or set, respectively.

  c) This 16KiB-bank 5 or 7 (according with bit 3 written to port $7FFD) **does not** need to be mapped at run-time into a slot.

  d) The high bytes of the offsets within 16KiB-banks 5 or 7 of the tile map and the tile definitions must be written to nextregs 'Tilemap base address' $6E and 'Tile definitions base addresss' $6F.

It is (c) that I am at present unclear about, based upon to my mind ambiguous statements made in zx-next-dev-guide-r3.pdf

Could someone please answer the following questions:

Q1) What is the scope of an MMU pseudo-op?

  My current (mis)understanding is that it is from the line of the MMU pseudo-op onwards in the file until either:
   (i)  The end of file, or
   (ii) The next MMU pseudo-op mentioning the very same slot, if such an MMU exists in the file.

Q2) Is my understanding correct that sjasmplus's "default banks" are equivalent to the implicit MMU pseudo ops:

    MMU 0, 14
    MMU 1, 15
    MMU 2, 10
    etc. as tabulated above?

Q3) What does the MMU 'e' option warn about, precisely? It has not warned about out-of-slot assembly in any of the cases here.

Q4) Notwithstanding the conflict with code in the MY_TILEMAP_SLOT EQU 6 case above, why is there _any dependency at all_ upon the value of MY_TILEMAP_SLOT? According to my (mis)understanding, this slot should not matter (generated machine code is invariant) as long as the **physical bank** the tilemap resides in is 16KiB-bank 5 (no shadowing is used here).

**Comment by OnceBitten** [comment]
I should have made clear in the line of the table titled "nexload default maps" that the items for slots 6 and 7 are unlike the rest not defaults, but are the maps used in the code due to the SAVENEX.

**Comment by ped7g** [comment]
JFYI I think there was bug in CSpect about loading bank5 directly from NEX file not initializing some bank5 depended subsystems correctly, like tilemode, but as you have at least one combination working, I guess this got fixed already.

Can't right now/here try to assemble and run it myself, but I can try to answer some of the questions without that:

------------
> Q3) What does the MMU 'e' option warn about, precisely? It has not warned about out-of-slot assembly in any of the cases here.

should warn when you cross the boundary by emitting the machine code, ie.
```
  MMU 1 e, 20, $3FFF  ; slot 1 ($2000..$3FFF page 20, ORG $3FFF)
  DB 123   ; no error, fits into slot
  DB 124   ; error, leaks outside of slot
```
Sounds like it did not warn you when you used -256 map offset, I will try to replicate to see what was that about, sounds like bug (or maybe you just exactly didn't cross the boundary :) )

By doing the +$2000 ORG you escape that target slot, which means you are **probably assembling tile map and data into wrong page** (MMU works with Next-native 8ki pages, it doesn't care about 16ki way of original ZX128 or NEX file format).

Whether ORG should error/warn about escaping the error boundary - I guess that makes quite some sense, but I didn't think about that when I was adding this feature, so it works differently. I can see how you are confused about that, your reasoning makes lot of sense, but I will be somewhat reluctant to change feature behavior, need to think about the benefits, the current solution is less annoying if you know what you are doing (you just move on next part of project doing new ORG and don't bother to cancel the "e" of that slot unless you need the slot again), but puts more onus on the coder to know what they are doing.

I guess in your case you want rather something like
```
  ; change two slots 6+7 mapping whole 16ki bank at $C000
  MMU 6 7, Next.TILEMAP_8K_BANK, MY_TILEMAP_SLOT_START + Next.TILEMAP_LOWEST_MAP_OFFSET
tilemap: DB ....
tiledef:   DB ...
 ASSERT $ <= $10000 ; manually asserting you didn't run out of the 16ki bank
 ; that assert then "simulates" what MMU "e" option can do for 8ki slot
```

------------
> b) They must both occur in same 16KiB-bank as the ULA Layer, thus 16KiB-bank 5 or 7 according as "shadowing" bit 3 of 'Memory Paging Control' port $7FFD is reset or set, respectively.

16ki of Bank5 and 8ki of Bank7 (first half of it) and port 7FFD is not involved in any way, tilemode doesn't react to the "shadow" screen of ZX128, only to the tilemode next registers.

> c) This 16KiB-bank 5 or 7 (according with bit 3 written to port $7FFD) does not need to be mapped at run-time into a slot.

yes, similar to Layer2 which also displays without being mapped into CPU address space. If you care about HW details, Bank5 and half of Bank7 are hijacked by FPGA and CPU instructions reading/writing there don't go into physical SRAM chip, but instead affect FPGA internal BRAM memory, so the FPGA video signal generator has access to these 24ki of memory instantly without using address bus and waiting for external memory chip. And that's also reason why only first half of Bank7, because there was not enough FPGA BRAM to use full 32ki shadow.

> d) The high bytes of the offsets within 16KiB-banks 5 or 7 of the tile map and the tile definitions must be written to nextregs 'Tilemap base address' $6E and 'Tile definitions base addresss' $6F.

yes, also in newer cores the bit 7 now selects bank 5/7, bit 6 is still ignored, remaining 6 bits are the offset value (you can compare current [nextreg description](https://gitlab.com/SpectrumNext/ZX_Spectrum_Next_FPGA/-/blob/master/cores/zxnext/nextreg.txt#L700) vs [old description on wiki](https://wiki.specnext.dev/Tilemap_Base_Address_Register) for core 3.1.5).

------------
Also it seems you are trying to avoid sysvars, but by putting these values into bank5 in NEX file, the whole Bank5 is stored in the file, so the sysvar area is loaded from your NEX file any way, being zeroed in your example. To truly avoid damaging it you must not include Bank 5 in the NEX file at all, put the tile data into other bank first and then at runtime copy them to bank 5 overwriting only the desired area of it.

------------
> Q1) What is the scope of an MMU pseudo-op?

Your current understanding seems correct to me, after `DEVICE ZXSPECTRUMNEXT` you have 64ki out of 2MiB of memory mapped to $0000..$FFFF all the time (starting with default mapping). Each `MMU` (or SLOT+PAGE) affects following code until you remap particular 8ki slot again with another MMU. The virtual device works sort of like the real device during runtime, but instead of using MMU registers you use MMU directive of assembler to map in/out desired pages.

> Q2) Is my understanding correct that sjasmplus's "default banks" are equivalent to the implicit MMU pseudo ops:

yes.

------------
> Q4) Notwithstanding the conflict with code in the MY_TILEMAP_SLOT EQU 6 case above, why is there any dependency at all upon the value of MY_TILEMAP_SLOT? According to my (mis)understanding, this slot should not matter (generated machine code is invariant) as long as the physical bank the tilemap resides in is 16KiB-bank 5 (no shadowing is used here).

I will try to check your example myself, but my guess is because of changing only 8ki slot and assembling into next one, so you usually don't assemble to the page you intended, but other one.

**Comment by OnceBitten** [comment]
Yes, I forgot to MMU the subsequent 8KiB slot  - slaps hand to forehead! These were not (explicitly) mapped except in the MY_TILEMAP_SLOT=5 case where it was already mapped for program instructions, so the default was used in those cases. Adding a second MMU line to map the subsequent slot:
`MMU MY_TILEMAP_SLOT+1 e, Next.TILEMAP_8K_BANK+1`
cures the problem. However,  if I then replace the `org` line:
`  ORG MY_TILEMAP_SLOT_START + Next.TILEMAP_LOWEST_MAP_OFFSET`
with
` ORG MY_TILEMAP_SLOT_START + Next.TILEMAP_LOWEST_MAP_OFFSET - 256`
there is still no error message despite the 'e' options.

I get your point re sysvars, and thank you for it, but for now I am only interested in a quick-and-dirty method of producing a tile map display. zxnDMA-transferring the tile map data into place will be done later.

Thank you for the information, including the brief hardware description, concerning tile maps. If I have understood you correctly, the tile map and tile definitions data can be located on any 256-byte boundary in 8KiB-banks 10, 11 and 14, independently of bit 3 of port $7FFD. If the ULA is being used, then this will reduce which positions can be used in these three banks, of course. Is this correct?

**Comment by OnceBitten** [comment]
Oh, I should add to that last paragraph: "And the tile map and definitions data must fit within those banks 10, 11 and 14.".... ;)

**Comment by ped7g** [comment]
The error/warning about crossing the slot boundary could indeed be lost in some cases, fixed.
And I did add check for the third "ORG" argument of MMU, so now it will warn you when you are using address which is outside of range adjusted by that MMU instruction. (doesn't affect standalone `ORG` as that one can mean intentional escape of confinement).

For example on Next `MMU 1 3, 20, $8000` should now warn about address 0x8000 being outside of 0x2000..0x7FFF range (slots 1..3).

**Comment by OnceBitten** [comment]
Thank you very much for your work on this, Peter
