### ISSUE TITLE
Error while loading a third party lua C module

### ISSUE THREAD

**Issue by fmafma** [z00m128/sjasmplus#248]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.20.3 	| linux 	| require() | 

I'm trying to use **lpeg** from **sjasmplus**, but I encounter an error while loading the module (require):

```error loading module 'lpeg' from file '/usr/lib/x86_64-linux-gnu/lua/5.4/lpeg.so'(0): error: [LUA] undefined symbol: lua_gettop```

The module is installed from debian `apt` package manager (lua-lpeg), and is located in`/usr/lib/x86_64-linux-gnu/lua/5.4/` dir. Unlike from Lua interpretor launched from a shell, where all works fine, I had to add this dir in `package.cpath` var or it won't load.

`lua_gettop` seems to be a standard function in Lua, so I don't understand how it can't find it...

Any idea what's going on?

Thanks,

**Comment by ped7g** [comment]
**Idea**: you did build sjasmplus yourself (as intended) and it used the bundled source code for [lua](/z00m128/sjasmplus/tree/master/lua5.4) which is version 5.4.6. The apt installed module is maybe built against different version (although the path contains "5.4" so it shouldn't be way off, I would even expect it to be compatible), the one provided also by Debian repository.

Try to build sjasmplus with OS lua instead of the bundled sources, if you are using Makefile then try `make clean`, then `USE_BUNDLED_LUA=0 make` .. -> this should build sjasmplus in a way that it will use the system lua shared library, try to launch it and use lua_lpeg then, if it works with such build. Then `make install` with your install prefix or sudo, depending where you prefer the binary to reside.

oh, I guess you are maybe using cmake to build it, then select the `SYSTEM_LUA` option to ON and rebuild with cmake.

---

Please report back if any of this makes sense and what results you did encounter, if this does help or it makes the build choke elsewhere or it builds but the lua_lpeg still fails to work, etc... So I know if I should look into this further and think of other ideas, or this was it. TY.

**Comment by fmafma** [comment]
> Try to build sjasmplus with OS lua instead of the bundled sources, if you are using Makefile then try `make clean`, then `USE_BUNDLED_LUA=0 make` .. -> this should build sjasmplus in a way that it will use the system lua shared library, try to launch it and use lua_lpeg then, if it works with such build. Then `make install`

That fixed the issue, thank you very much!
