### ISSUE TITLE
Current module name

### ISSUE THREAD

**Issue by fmafma** [z00m128/sjasmplus#251]
Hi!

Is there a way to get the current module name, from LUA code?

Best,
Fred

**Comment by ped7g** [comment]
I don't think so.

I'm considering adding some new API+binding for it, but not sure what to return.

One thing which shouldn't be too tricky to add is to return current full prefix (what would be prepended for next new local label) - which does include all nested modules and last main label as well like `module1.module2.mylabel` (this becomes unfortunately impossible to split correctly if user does use dots in the module names or main labels, but as long as you are author of the code, it's up to you to avoid dots in names).

I think I should be able to extract also just current module (without the outer modules and without the main label) because I should be somehow able to remove it from prefix when `endmodule`, but that may be more tricky. I will have to take deeper look into implementation.

Anyway, the main purpose of this comment is to let you know that I'm planning to take a look somewhere in the future.

**Comment by fmafma** [comment]
Thank you!

**Comment by lordheavy** [comment]
https://github.com/z00m128/sjasmplus/pull/252

**Comment by ped7g** [comment]
Done on master branch.

While doing this, it became known to me the sj.insert_label does treat input string "verbatim" adding the label as is without applying namespace/main label, etc..

that's IMHO a bug and will be fixed too (although it's maybe more powerful API for power users, I think it's not convenient and not in "spirit" what would regular user expect).
