### ISSUE TITLE
Problem with macro and underscores

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#35]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.10.4   	| mac	|

Hi,
I have been running into a problem with macros.
It seems that **certain number of argument and underscore combinations are not correctly parsed**.
Loot at this example:

```
    ORG 0x0000

    MACRO MYMACRO addr, string, term
        ld de,addr 
    ENDM

test_result_string: defb 0

    MYMACRO test_result_string, 1, 0
```
This gives the error:
src/main.asm(19): error: Label not found: test_result_1

I.e. it seems that first and 2nd argument are somehow concatenated.

Almost the same macro with only 2 arguments works:

```
    ORG 0x0000

    MACRO MYMACRO addr, string
        ld de,addr 
    ENDM

test_result_string: defb 0

    MYMACRO test_result_string, 1
```

Also this macro with 3 arguments but first argument with only one underscore works.
```
    ORG 0x0000

    MACRO MYMACRO addr, string, term
        ld de,addr 
    ENDM

test_resultstring: defb 0

    MYMACRO test_resultstring, 1, 0
```

 

Please note: the arguments are not used inside the macro just for simplifying the problem. Of course I will use them in the real macro.

**Comment by ped7g** [comment]
Well, there are multiple things in this involved...
> It seems that certain number of argument and underscore combinations are not correctly parsed.

Sure, the code is full of subtle bugs/features which most of the time remain unexposed.. I'm now digging through it for ~8 days, and the idea of "lets rewrite it all" keeps coming back almost every time I take a look. So the chance of something "not parsing correctly" is almost safe bet.

Actually it's even worse, as these subtleties are not described in documentation or in the code, so it's not clear what is wanted feature and what is bug.

The `_` character on source line functions as delimiter for `DEFINE/MACRO` substitution, i.e. the `string` part of label is detected and replaced by second argument of the macro. This is intentional by original sjasmplus authors, as in sources there was `macro_test.asm` which expects macro line `call arg0_arg1` to be expanded by replacing the two parts separately.

Not separating `string` from `result` part by `_` (or you can separate it by other label character like `?` for example which also documented as valid label character, but it does not work as delimiter for substitution) will avoid the `string=1` substitution (it's not about amount of underscores, but about identifiers collision).

In your case the substitution happens like this: `ld de, addr` -> `ld de,test_result_string` -> `ld de,test_result_1`

While there's hard limit for substitution depth (20) (try `MYMACRO test_result_string, string, 0`), it is not clear to me why the `string=1` happens when three arguments to macro are defined, but does not happen when two arguments are defined only. That's bug of the substitution algorithm (probably some too early exit from loop), I think it would be more correct if it would end with `ld de,test_result_1` even with only two arguments defined.

I would suggest to avoid identifiers collisions in the first place (for example naming macro argument as `ld` may bring lot of fun into the assembling process). Maybe use something like `MACRO MYMACRO addr?, string?, term?` (or even `_string` argument name does inhibit substitution, but I can't explain why, that seems to me like another bug).

Unfortunately the way I understand the current situation - the "no action" seems to be the most correct solution. As the two-argument substitution is documented wanted behaviour by original authors, while fixing the subtle bugs which would make the substitution more robust and predictable would just lead to your error message more reliably, not removing it.

I.e. I'm afraid you have to modify your code to avoid the `string` identifier collision with the actual label name.

On the sjasmplus project side there should be substantial effort put into documenting the wanted behaviour first, as the documentation is seriously lacking in this aspect, not even explaining why `arg0_arg1` should work as it does in that test asm file.

And after the desired behaviour is documented well, it would be possible to fix the code to follow it rigorously, but at this moment I'm afraid any "fix" of this behaviour may just as well introduce new problems for some other users.

I think this is in a state when "close, because it's feature, not bug" is imminent, but maybe I'm missing some further details, so feel free to comment/expand/ask if you don't agree about such resolution.

**Comment by maziac** [comment]
Seems quite complicated to solve.
No problem, I will simply remove one underscore then it works for me 
and we can close this :-)

**Comment by ped7g** [comment]
I would rather use the question mark in arguments identifiers, seems to me quite OK to read such source... `ld de,addr?`   => my mind goes "ok, this does ask for value somewhere" (into macro arguments values). And that makes further identifier clash sort of impossible as long as you don't use question mark also as part of data, or for your regular labels (I would not).

Removing underscore will help you in this particular case, but you can still produce some macro-argument-identifier by accident in future (all it takes is another label like `summary_string` and there you go again...

**Comment by maziac** [comment]
Agreed. Seems the better solution. I use the question mark now.

**Comment by ped7g** [comment]
So... after refactoring of related code, I finally understood the original Antipod's patch and how it was designed to work, and why the 2 argument macro in your code was not substituting it, but 3 argument macro did.

Old rules: the `_` is delimiter of parts designed for substitution, i.e. `test_result_string` is giving "preprocessor" 3 possible sub-parts for separate substitutions, but the mechanism is triggered only if the first letter of the main string is equal to first letter of one of the defines/macro-arguments OR when the first letter is the delimiter itself. So in your two argument macro the `addr` did substitute, and then it was starting with letter `t`, but there was no define/argument with letter `t`, so the mechanism didn't kick in. The three argument macro has third argument `term`, causing the second round of substitution to happen, where the `string` sub-part is found and replaced.

New rules after refactoring:
* the sub-part substitution is now always on, lot more aggressive than before (so it may break some old sources, if somebody was using many defines or macro arguments and was using too common/short names for them) - but one shouldn't end scratching his head, why something is affected and something not, all should be affected.
* The sub-parts is recursively combined, i.e. `test_result_string` is considered for substitution as { `test_result_string`, `test_result`, `result_string`, `test`, `result`, `string` } (and all the variants with leading/trailing underscores where possible, but that explodes the amount, so I listed only the major ones)
* define/macro-arguments starting with underscore (like the built-in `_VERSION` define) can be substituted only from the beginning of the string, i.e. your own `test_result_VERSION` is safe from sjasmplus (at one point of refactoring I got into situation where I got such substitutions :), so I introduced this rule)

How to avoid accidental substitutions...
* start macro arguments and defines names with underscore, if you are not planning them to use as in-the-middle substitutions.
* ending them with question mark still sounds like a good way to prevent most of the typo-like accidents (and it doesn't inhibit in-the-middle substitutions, if you actually want to use them)
* don't use generic names for defines and macro arguments, try to keep them very specific to their function, so they are unlikely to clash with unrelated strings in the source.
