### ISSUE TITLE
list format, pluses

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#36]
I found that the list format has slightly changed on the current master branch.
My z80-debug tool depends on this format and so I ran into problems.
This as such is not a big problem, I can adjust.
But I noticed that the number of possible "+"s has been reduced from 3 to 2.

The pluses indicate the nesting level e.g. for every include a "+" is added.
My z80-debug extension uses this information to determine the right source file name from the list file.

In the list file the number of pluses is restricted. So a maximum of 2 is now displayed.

In the past I saw 3 pluses as a maximum for the list file and this already was a bit problematic. It meant that with 4 nesting levels my extension might not choose right source file.
But now with 2 pluses only this situation is even more probable.

So, my request is:
- Can you please not reduce the number of maximum pluses any further so that at least 2 pluses will be there
- or maybe don't restrict the number of pluses at all 
- or make this configurable on the command line.

**Comment by ped7g** [comment]
> But I noticed that the number of possible "+"s has been reduced from 3 to 2.

Well, that's not technically true, see for example: [nested_includes/i36.lst](/z00m128/sjasmplus/blob/master/tests/misc/nested_includes/i36.lst)

So what is happening on master branch right now:

---------
the listing formate is modified in fixed-width way, where each column has always same content.

The first 6 chars are line number plus nesting level indicator, which allows for line numbers up to 99999 to be listed correctly (further lines will use more ASCII codes beyond '9' for first digit, until `~9999` is reached). The width used for line numbers depends on the largest one reached. The remaining characters up to total of six are used for nested-level indicator (so with single digit lines there's enough room for five "+", you having only two "+" means you have four digit line numbers).

Then four characters show 16 bit memory address, then comes one space.

After that there are (up to four) machine code bytes in hexadecimal, each separated by space, or symbol `~` for lines which were skipped due to condition (`IF`/etc.). If the actual machine code is longer than four bytes, remaining bytes are listed on following lines (showing empty source line).

At 24th character there's indicator of normal (space) and macro/dup (`>`) source line, and from 25th character the source line is copied.

---------

This should be of benefit for fixed-width parsing of listing files (you can basically reconstruct both machine code or source just by cutting out desired columns and do some minimal filtering/parsing upon them), but it limits available space for some indicators, like nesting level.

This is currently "experimental" work in progress, so it's great to get this feedback, it will help to polish this before next release.

> My z80-debug extension uses this information to determine the right source file name from the list file.

Couldn't you rather extract it from previous line with the INCLUDE directive? (when the line number gets reset to 1, the previous line may contain `INCLUDE` directive with the file name - unless the line number "1" is achieved by other means (I can think of "long machine code" and DUP/REPT macro maybe))

I would even consider adding line "0" to listing file, which would contain just full filepath name of current source file, I will certainly ask about that the other guys, if it's viable.

> or make this configurable on the command line.

And that's another option, how to deal with it, although I would prefer to resolve this "properly" (your counting of nest-level to deduct file name sounds to me a bit hack-ish, or I maybe misunderstood what you actually do).

**Comment by maziac** [comment]
Hmm,

1) am I missing a parameter or something: I get max 2 pluses. Here is an excerpt of my list file:
```
  10  0000
  11  0000               IF 01 
  12  0000                  include "i1.inc"
   1+ 0000
   2+ 0000              i1:
   3+ 0000 00               nop
   4+ 0001
   5+ 0001                include "i2.inc"
   1++0001
   2++0001              i2:
   3++0001 00               nop
   4++0002
   5++0002                include "i3.inc"
   1++0002
   2++0002              i3:
   3++0002 00               nop
   4++0003
   5++0003 00               nop
   6++0004
   7++0004                  
   6++0004
   7++0004 00               nop
   8++0005
   9++0005                  
   6+ 0005
   7+ 0005 00               nop
   8+ 0006
   9+ 0006                  
  13  0006               ENDIF
  14  0006
  15  0006
```
There are max 2 spaces not 5 like in i36.lst

2) Fix-width parsing is fine but isn't this contradictory to your other statement: "The width used for line numbers depends on the largest one reached".  Anyway, no big deal. One can just read the complete file first to read the last line.

3) 

> Couldn't you rather extract it from previous line with the INCLUDE directive? (when the line number gets reset to 1, the previous line may contain INCLUDE directive with the file name - unless the line number "1" is achieved by other means (I can think of "long machine code" and DUP/REPT macro maybe))

The problem is not to find the beginning of the include but to find its ending.
I'm trying to find the end by looking at the line number and the number of pluses. If the number of pluses reduces then the include file ended. But also if the line number is not the expected next line.
This works in 90% of the cases but it fails in the following case, e.g.:
The main-file with the include statement includes inc-file at line 10. The size of the inc-file is also 10.
So the line that is expected after line 10 of the inc-file is 11 and that is also the same line as the line after the include statement in the main file.

> I would even consider adding line "0" to listing file, which would contain just full filepath name of current source file, I will certainly ask about that the other guys, if it's viable.

This would be really great. Would simplify the parsing a lot.
But still I would also require a unique way to find the end of the included file.

The z80-debug is currently parsing sjasmplus, the z88dk assembler and Savannah's z80asm.
With z88dk I have a similar problem, here it is even worse as they don't include any nesting level information.
It's best working with Savannah's z80asm. It, too, doesn't have a nesting level but it has clear end markers, e.g.:
```
5cc8 15                  defb 015h      ;5cc8     15   . 
5cc9 50                  defb 050h      ;5cc9     50   P 
5cca 80                  defb 080h      ;5cca     80   . 
5ccb           ; end of Reserved area 
5ccb           END_RESERVED_AREA: 
# End of file zxspectrum_data.asm
5ccb            
```
As start marker I use here the include directive and as end marker the "End of File..."

The best would be to have a clear start and end marker with file name and maybe nesting level.
I.e. if no nesting level is included in start and end markers then it would be nice to have the filename (full path) in both markers. If a nesting level is included in the markers then the filename is only required for the start marker.
I would prefer the latter because this would also work in situations were there are several nested include files with the same name. See e.g. the i36.lst.

**Comment by ped7g** [comment]
>  am I missing a parameter or something: I get max 2 pluses. Here is an excerpt of my list file:

I mean the whole block "line number AND nesting level" is constrained to 6 characters. And then inside this 6 character block the division is dynamic, form 1:5 to 5:1, depending on the maximum number line used in any source included, so in your case there is at least one file with line inside 1000..9999 range, which makes the whole block 4:2. ... It's just explaining what it does, it's not making your problem to go away, you are correct, that in your case you get only max two + marks.

But it seems your true issue is detecting begin/end of the source file, so at this moment I would first ignore the nesting level indicator and focus to bring the new markers similar to what you described.

Although it will be not 100% identical to Savannah's because that would pollute the machine code columns, but something almost identical, just aligned into source area, may be possible.. just not sure about line number and memory address columns yet, that's up to discussion... But I guess you don't mind slight differences and can work around it in your parsing.

**Comment by ped7g** [comment]
thinking about it, another option is to modify the nesting indicator from plain "++++" to something like "+++>" at first line of new file and "++<" upon return, but make this last character to be displayed as last visible (so in case there's only single column for nesting, it would go like `[_,_,>,>,+,<,+,<,_]` (two nested includes) instead of `[__,__,>_,+>,++,+<,+_,<_,__]`.

Also one thing is some nice idea, other thing is what the sjasmplus source will allow within reasonable amount of modification... :) (so I can't promise anything, also staying "compatible" with older versions is of huge priority, so any behaviour change like this is kind of risky and may backfire badly in some case we didn't envision).

**Comment by maziac** [comment]
It doesn‘t have to be Savannah‘s format. I‘m quite free in the parsing process. It is only important that the nesting and file information allows for a unique identification of the file.

The > and < would help but only if it is assured that they are not truncated. So maybe it would be better if it starts with < or > instead of ending, e.g. >++ and <++.

**Comment by maziac** [comment]
BTW thanks for including the ZXNext opcodes. I exchanged all my macros now. It's working fine.

**Comment by ped7g** [comment]
The proposal to add "zero" lines with full path info has been basically approved by few people.

Now the approval from sjasmplus source code itself is needed (if it will not defend too much and let itself bend a bit, it may happen).

**Comment by ped7g** [comment]
Please check [this commit](https://github.com/z00m128/sjasmplus/commit/0d0a2a95fcccf4224a82fff25d75df13ffb77a8e) where you can see how the master-HEAD was modified to produce this extra info. Let me know if this is somehow not good (like difficult to parse, or you expected some other extra info), and what is missing.

Probably check mostly [tests/misc/nested_includes](../tree/master/tests/misc/nested_includes) and [tests/test build script and options/include_paths](../tree/master/tests/test%20build%20script%20and%20options/include_paths) to see non-trivial examples of it in action.

**Comment by maziac** [comment]
I just checked and found double slashes in the file paths:
```
# file opened: src/main.asm
   1  0000              ;========================================================
   2  0000              ; main.asm
   3  0000              ;
   4  0000              ; Main program to call the other framework components.
...
  37  004B
  38  004B
  39  004B                  include "zxnext/zxnext_regs.inc"
# file opened: src//zxnext/zxnext_regs.inc
   1+ 004B              ;=======================================================================
   2+ 004B              ; ZX Next specific constant, registers and ports.
   3+ 004B              ;=======================================================================
   4+ 004B
```

Most probably this is not intended.

**Comment by ped7g** [comment]
This is highly likely because the include path is set as `-Isrc/` and the code will "strcat" the two strings with another `/` explicitly inserted between.... IIRC this is benign and the `fopen/fclose` will operate correctly even with double-slash path, but I will check the code if I can avoid this (hopefully only "aesthetic" problem).

So otherwise is this fine for you?

**Comment by ped7g** [comment]
It was (yet another) bug in the original sources picked up at the beginning of this fork project.. +1 wrong index. :) (you can still produce double slashes intentionally, like doing `-Ipath//` on the command line, but I don't think it's worth to build robust path-fixer into assembler, so only trivial case is handled).

**Comment by maziac** [comment]
Could verify that the paths are working now.

**Comment by ped7g** [comment]
This is kinda offtopic, but I guess you have notifications ON over this issue, and it's about listing format...
In v1.11 there was one more change to listing files, the machine code area may now look also  like this:
`02 02 02...`  = with the three dots connected to previous byte. That signals the source line did emit many bytes (five or more, four would fit without dots), but only three of them are show in listing. May happen with lines as `ALIGN 0x1000` or `BLOCK 10,0x02`, or with structures using align/block fields.

If you are actively parsing code-bytes area, this may eventually break your scripts/code, sorry for the inconvenience (the change was needed due to some edge cases in structures, where the produced byte-list was wrong without signalling any shortcomings/warning to the reader, now the dots do that).

**Comment by maziac** [comment]
No problem. Thanks for info.
