### ISSUE TITLE
new label in labels file

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#43]
I'm not sure if this is a bug or if I'm interpreting something wrong.
Anyhow I think that this behaviour is at least strange.

Look at the following code:
```
    ORG 0x8000

 MODULE ma 
lb: equ 6
 nop
 ld a,lb
 ld a,ma.lb
 ENDMODULE
```

The code compiles without warning.
I used the following commandline:
```
sjasmplus --lst=main.list --sym=main.labels --fullpath main.asm
```

The list file results into
```
12    8000               MODULE ma
13    8000              lb: equ 6
14    8000 00            nop
15    8001 3E 06         ld a,lb
16    8003 3E 06         ld a,ma.lb
17    8005               ENDMODULE
```
which seems correct.

But the labels file output seems strange:
```
ma.lb: equ 0x00000006
ma.ma.lb: equ 0x00000000
```
It generates a new label ma.ma.lb and initializes it to 0.

**Comment by ped7g** [comment]
I would interpret this as bug, but giving it somewhat low priority at this moment (also see my comment in issue #42 if you want to know what I think about current label handling) :) ...

**Comment by ped7g** [comment]
The difference between listing with labels (not showing that extra symbol) and symbols file is, that listing file didn't show labels which remained undefined, while symbols file dumps the whole table completely.

Rather than limiting dump of symbols file, I tried to make insertion of the extra symbol unlikely (works for the code in Issue of course).

Still, if you will do for example `ld a,ma.lb3` without defining `lb3` anywhere in the file, the listing labels table will omit `lb3`, but `--sym` symbols file will show it as zero-value label (= undefined), so the the two ways how to dump labels still produce different results (intentionally at this moment).
