### ISSUE TITLE
SAVETRD improvement

### ISSUE THREAD

**Issue by ammehet** [z00m128/sjasmplus#56]
When using SAVETRD with existing trd image that already contains code file with same name, sjasmplus just adds another one (with the same name) to the end.
For example, there's image.trd containing mycode.C. Then if I use SAVETRD "image.trd","mycode.C",start,end-start, I'll have two mycode.C, one after another. TR-DOS allows that, but can access only the first one.
For some reason, I've a bunch of files on the image, so using EMPTYTRD and copy them all back is not a good idea.
It would be very useful to mark previous mycode.C as deleted before adding a new one. (this fork behaves like that as well https://github.com/sjasmplus/sjasmplus)

**Comment by Liniya** [comment]
This behavior is sometimes useful too, for instance in a 'monoloader' you can just dump all the BIN's to a TRD as 'Data.C' or something sequentially without having to extract/set TRD filenames etc since it doesn't matter. Perhaps if it can be made optional, or possibly an additional directive like REPLACETRD... But making overwrite the default behavior for SAVETRD is a bad idea I think. - Just my 2c, anyway.

There's a number of TRD tools in circulation that allow more advanced operations like delete/move. So in the meantime you can probably try to make up for it by defining a LUA function like this:

```
	-- replacetrd.lua
	-- use INCLUDELUA "replacetrd.lua" in sjasmplus

	-- set a variable to point at the path to your TRD utility
	trdtool = "C:\utility\maketrd.exe"

	function zx.trdimage_replace_file (imgname, filename, addr, len, autostart)
		-- change these to use the appropriate syntax for the TRD utility
	 	   sj.shellexec(trdtool.." --deletefile "..imgname..' '..filename)
		   sj.shellexec(trdtool.." --move "..imgname)
		zx.trdimage_add_file(imgname, filename, addr, len, autostart)
	end
```

Then use it in sjasmplus like:
```
	LUA PASS3
	 zx.trdimage_add_file("myimage.trd", "myfile.C", 16384, 6912, 0)
	ENDLUA
```

It's also possible to wrap this call in a single REPLACETRD macro so it behaves (almost) like a native operation. See [here](https://github.com/z00m128/sjasmplus/issues/46#issuecomment-482171632) for a way to pass macro arguments to LUA.

**Comment by ammehet** [comment]
> for instance in a 'monoloader' you can just dump all the BIN's to a TRD as 'Data.C' or something sequentially

And how do I know they are written in the correct sequence? Isn't it better to name them data1.C, data2.C, etc?

> But making overwrite the default behavior for SAVETRD is a bad idea I think.

Can't imagine a situation where someone wants to have several files with the same name in the same space (directory). This behavior is not typical even for TR-DOS itself. Version 5.04T simply refuses to write the file with message "File exists", and 6.11Q will ask for overwrite.
I also can't imagine any purpose why to keep previous version of _compiled code_ in development image, when the source code is rebuilt every few minutes. Especially as TR-DOS can't access the newer one.
I agree that _adding_ file with the same name can be optional, but default behavior should be to mark previous as deleted. Not overwrite. You can "undelete" it by changing single byte with any hex editor.

**Comment by ped7g** [comment]
> Version 5.04T simply refuses to write the file with message "File exists", and 6.11Q will ask for overwrite.
For me (as non TR-DOS user) this is quite strong (enough) argument for auto-rewrite by sjasmplus too.

> why to keep previous version
that's what git does, so I don't see any point too.

> but default behavior should be to mark previous as deleted.
Any specifics, which bytes to overwrite and where and to which value? That can make the addition quicker (as I don't understand TR-DOS and TRD, I will have to search for all this info ... let's hope the io_trd.cpp contains some comments about header and TRD structure, but still having precise guideline would save me lot of research time.

**Comment by Liniya** [comment]
>For me (as non TR-DOS user) this is quite strong (enough) argument for auto-rewrite by sjasmplus too.

Really now. It's a counter-argument if anything, as it follows that you would be replacing one non-TR-DOS like behavior with another non-TR-DOS like behavior for no clear reason (most people just use EMPTYTRD and think nothing of it, anyway). It shouldn't be a concern what happens in DOS versions above 5.04T in the first place if you want to approach it from that angle, as they are mostly little-known hacks specific to individuals and/or particular Spectrum clones, not in wide use.

I consider it reasonable yet to make it an optional parameter like 'autostart', but definitely not change the default behavior.

**Comment by ped7g** [comment]
about syntax: ok, seems like replace should be new extra and not default... not sure what to pick for it, how about `savetrd "image.trd",!"file.C", 10, 20` where the `!` means the file should be replaced if it already exist.

about implementation: I took a quick peek at TRD image structure, and ... again, not sure how to deal with it. If the "file.C" is last directory entry, it's probably simple to overwrite it and update image, but if it is not last entry, either sjasmplus would need to reshuffle whole image and optimize the entries, or it may just delete the old one and add new. In that case overwriting single last file in image would work nicely, but if you would write for example two different files with each build, it would fill up directory entries (128 max) over time (deleting + adding new), requiring you to prepare new image from time to time.

I'm almost sure I don't want to implement full disk image shuffler/optimizer into sjasmplus, so rather expect some dumb-simple implementation like "optimal overwrite only if last entry".

If I would have project like that, I would personally rather use make+Makefile to build it, and copy pristine original TRD image (without the files created by ASM source) from backup file as early step of every build, and then run sjasmplus writing the new files into the new copy of image = works already with current version. And I use Makefiles also for graphics files conversions/etc, so the `incbin` in asm source has always fresh data, so for me it would mean just to add one more rule to Makefile and one more prerequisite condition for asm file (like 3-4 new lines).

**Comment by ammehet** [comment]
> about syntax: ok, seems like replace should be new extra and not default... not sure what to pick for it, how about `savetrd "image.trd",!"file.C", 10, 20` where the `!` means the file should be replaced if it already exist.

Or there could be additional optional argument like this
`SAVETRD "image.trd","file.C",start,len[,R[EPLACE]]`

> I'm almost sure I don't want to implement full disk image shuffler/optimizer into sjasmplus, so rather expect some dumb-simple implementation like "optimal overwrite only if last entry".

Don't bother with last entry or shuffling image contents, just mark the file as deleted. To do so you have to replace first letter of deleted file name with 0x1 and increment deleted files counter at track 0 sector 8 (disk specification sector) offset 244 (0xF4). Then add new file(s) as usual.

However, "optimal overwrite only if last entry" will be greatly appreciated =)

Full description of TRD disk image format can be found here http://www.zx-modules.de/fileformats/trdformat.html

**Comment by ped7g** [comment]
Some final comments: sjasmplus/sjasmplus project has IMO much nicer implementation now, but it does only replace files I believe (not possible to create two files with identical name), so in the end I decided to not copy it and rather fixed the old source to keep this quirk functional... And I'm not really happy with the result in terms of source quality, but should be "good enough" for now.

About syntax of "replace": in the end I went for the pipe character ahead of file name. While I did like your suggestion to add ",replace" as last argument, I did find out there's already one optional last argument providing "autostart" line number for BASIC programs, which was complicating this a bit (what if somebody would do `R EQU 1234` and expect `SAVETRD .....,R` to use that as autostart value?). While pipe can't be legal part of filename, and normally it is "OR" operator, so it's slightly connected to the meaning of "replace" ... ok, I'm bending it too much :) . The truth is, that I wanted to finish this, it took already more time than expected (there were multiple bugs in old implementation, so instead of spending my time to just add "replace" I had to fix multiple bugs first, to prevent sjasmplus from damaging TRD imagines in certain situations (you can check commit message for list of bugs)).

The docs linked by you at least helped to resolve some questions I had (the docs I did find elsewhere contain more typos and missing details), although for example I still don't know if zero-length files are legal in TRDOS and how precisely they are stored (if they occupy at least one sector or zero sectors), and also I found out the maximum length of file is actually only 0xFF00, while the old implementation was checking length against 0xFFFF ... All these small inaccuracies, talk about different TRDOS versios, etc... is making this topic very unattractive for me. I like things which are well defined, with all corner cases covered, this TRDOS thing is kinda annoying. I just hope I didn't "break" some use case of sjasmplus user by adding the extra validations and fixes...
