### ISSUE TITLE
new macro syntax

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#57]
This is strange.
I update to new version 1.13.1 (last commit 81dd0cbe187a86737a8527a91e8a3fb56da7f107) and tried out the new macro syntax.

I took the code from the example 
~~~
LabelAsMacroName    MACRO  arg1?, arg2?
                        ld  a,arg1?
                        ld  hl,arg2?
                    ENDM

                LabelAsMacroName 1,$1234
~~~

But get the following error followed by a segfault:
~~~
sjasmplus --zxnext --inc=src --lst=out/zxngfw.list --sym=out/zxngfw.labels --exp=src/zxngfw.inc -DDEBUG --fullpath -DZXNGFW_BIN_FILE=\"zxngfw.bin\" src/main.asm  src/exports.asm 
SjASMPlus Z80 Cross-Assembler v1.13.1 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
Pass 3 complete
Errors: 0, warnings: 0, compiled: 5938 lines, work time: 0.020 seconds
sjasmplus --zxnext -DDEBUG -DSNA_FILE=\"out/ut_dbg.sna\" --inc=src --lst=out/ut_dbg.list --sym=out/ut_dbg.labels -DZXNGFW_BIN_FILE=\"out/ut_dbg_zxngfw.bin\" --fullpath src/unit_tests.asm 
SjASMPlus Z80 Cross-Assembler v1.13.1 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
src/unit_tests/ut_sprites.asm(729): error: Unrecognized instruction: LabelAsMacroName 1,$1234
Pass 3 complete
make: *** [out/ut_dbg.sna] Segmentation fault: 11
make: *** Deleting file `out/ut_dbg.sna'
The terminal process terminated with exit code: 2
~~~

Before you ask, I did a
~~~
make clean
make
make install
~~~

**Comment by ped7g** [comment]
it works for me without problems as stand-alone asm file with content you posted, can you try it like that, just the macro + emit?
```
$ sjasmplus --msg=lst Issue57.asm 
SjASMPlus Z80 Cross-Assembler v1.13.1 (https://github.com/z00m128/sjasmplus)
# file opened: Issue57.asm
1     0000              LabelAsMacroName    MACRO  arg1?, arg2?
2     0000 ~                                    ld  a,arg1?
3     0000 ~                                    ld  hl,arg2?
4     0000                                  ENDM
5     0000
6     0000                              LabelAsMacroName 1,$1234
6     0000 3E 01       >                        ld  a,1
6     0002 21 34 12    >                        ld  hl,$1234
7     0005
# file closed: Issue57.asm
```
I will try to use more options similar to what you do, maybe it's something there... Although I would rather expect it to be something from the previous lines of source.

The segfault comes after pass3 ... hmm... that may be actually something about macros/label teardown, so that may be related to the options (if it is, I will hopefully trigger it too).

But why the macro is not recognized, that's a bit a mystery to me. Any chance to provide me full zip? (ping me on discord for example)

**Comment by maziac** [comment]
Yep, alone it works for me as well.
Funny!

**Comment by ped7g** [comment]
I get segfault with slightly modified options of yours, but the macro works, so it's at least two issues in one... (maybe more, if my segfault is different).  So I guess the macro fails due to surrounding code, but I can't even imagine what triggers it. Probably some global var isn't reinitialized properly at some point...

**Comment by maziac** [comment]
Found the problem. It's the MODULE keyword.
Please assemble this code:
~~~
    MODULE ut_sprites


LabelAsMacroName    MACRO  arg1?, arg2?
                        ld  a,arg1?
                        ld  hl,arg2?
                    ENDM

                LabelAsMacroName 1,$1234


    ENDMODULE
~~~

It results in:
~~~
sjasmplus --msg=lst Issue57.asm 
SjASMPlus Z80 Cross-Assembler v1.13.1 (https://github.com/z00m128/sjasmplus)
# file opened: Issue57.asm
 1    0000                  MODULE ut_sprites
 2    0000
 3    0000
 4    0000              LabelAsMacroName    MACRO  arg1?, arg2?
 5    0000 ~                                    ld  a,arg1?
 6    0000 ~                                    ld  hl,arg2?
 7    0000                                  ENDM
 8    0000
Issue57.asm(9): error: Unrecognized instruction: LabelAsMacroName 1,$1234
 9    0000                              LabelAsMacroName 1,$1234
10    0000
11    0000
12    0000                  ENDMODULE
13    0000
# file closed: Issue57.asm
~~~

**Comment by ped7g** [comment]
The macro is then `ut_sprites.LabelAsMacroName`, because in modules the label defined has module prefix.

To avoid that, you can define the macro name as: `@LabelAsMacroName    MACRO  arg1?, arg2?` using "global" prefix for label definition.

I'm a bit torn on this, if I look at it as "**label** as macro name" then this works perfectly fine, just how labels are defined - except the actual macro name is not in the labels table (it's removed after macro is defined).

When you look at it as equivalent of original `macro name [args]` syntax, then this is bug, because `MACRO  LabelAsMacroName arg1?, arg2?` inside MODULE does define macro `LabelAsMacroName`.

I wrote into docs:
> If there is regular label defined on the line with MACRO pseudo-op, the label will be used as macro name - this may collide with true label using the same name, so this is NOT recommended syntax. It was added as compatibility convenience to make porting from different assemblers somewhat easier.

... hm... It's kinda stretching it really a lot, but one can say it's doing what it should do, it's "label as macro name", not "macro name at start of line" ;) ... then again it feels wrong and makes this convenience syntax different from `macro name [args]`, so I will probably check if I can get rid of the module part instead, and reword docs.

**Comment by maziac** [comment]
It's not so nice that the behavior is inconsistent.
But on the other hand it's only meant as a convenience for code written for another assembler which will most probably not support the MODULE keyword.
So you can also leave it as it is.
