### ISSUE TITLE
Bad CRLF handling in parser

### ISSUE THREAD

**Issue by z00m128** [z00m128/sjasmplus#8]
When CRLF line ending splits on 4k boundary (e.g. $1000, $2000 etc), line numbering goes wrong in listing (counts both 0D and 0A as separate lines).

Identified by mborik as bad buffer handling in _sjasm/sjio.cpp_.

**Comment by z00m128** [comment]
Fixed in v1.10.2.

**Comment by mborik** [comment]
There was misunderstanding because 612fcc8 not solving this particular issue with 4k buffer boundary and overflown LF after CR in files with Windows line-endings on Mac or Linux.

**[noter.zip](https://github.com/z00m128/sjasmplus/files/2296404/noter.zip)**
This is example file which has CRLFs that breaks on $1000 and $2000 boundary.
If you compile this file on Mac or Linux `sjasmplus --lst=output.lst noter.a80` you will see in the output listing another dummy lines generated after line 292 and 540, so all line references (in errors/warnings/messages) will be shifted by them.

**Comment by z00m128** [comment]
Attempt to fix in https://github.com/z00m128/sjasmplus/commit/bd4721b22a8ed6736f85111ec12646681961dcbf. Please test it. Thanks.

**Comment by z00m128** [comment]
Fixed in https://github.com/z00m128/sjasmplus/commit/bd4721b22a8ed6736f85111ec12646681961dcbf and/or in https://github.com/z00m128/sjasmplus/commit/eaf65ea057603afe391c11895e7373d865ec6b3f.
