### ISSUE TITLE
Nested local labels & macro labels

### ISSUE THREAD

**Issue by specke** [z00m128/sjasmplus#84]
**Is your feature request related to a problem?**

I have a code that used macros for repeatable items, but needs to also have access to positions inside of macros. E.g. this is what I would like to be able to do:
```
 MACRO Example1
.val EQU $+1
  ld a,0 : ld (hl),a : inc h : ret
 ENDM
 MACRO Example2
  ld a,(de) : ld (hl),a : inc h : ret
.val EQU $+1
  ld a,0 : ld (hl),a : inc h : ret
 ENDM
 ALIGN 256
Chunks:
 ORG Chunks+15*0
.C00 Example1
 ORG Chunks+15*1
.C01 Example2
```
etc etc

What I would like to be able to do is something like
```
 ld a,#05 : ld (Chunks.C00.val),a
 ld a,#07 : ld (Chunks.C01.val),a
```

However, this does not work, because local labels inside of macros are invisible outside of the macros.

**Describe the suggested solution:**

I believe that it would be useful to be able to nest local labels on the top of the local label. I.e., when inside of the macro, all local labels become suffices of the last label (local or not local). Ideally, this would recursively, so that macro inside of the macro should still be addressible.

Effectively, this behaviour is a particular case of nested local labels. The nesting gets one level deeper if the label is inside of a macro.

**Comment by ped7g** [comment]
> However, this does not work, because local labels inside of macros are invisible outside of the macros.

Technically, there is no such thing as invisible symbol within single compilation unit, to truly hide one symbol from other file, you need to launch sjasmplus individually for each unit (unit = you can put more file names as input line, then the multiple files see the labels between them).

The local labels in macros get special current-instance-of-macro prefix, like `0>val` for the first macro used in source. But you can't write such symbol name directly into instruction, as that is not valid label name, so this is of no help for you.

But currently it works the other way, macro can use local labels of the code which is using the macro, for example this is possible:
```
my:
.local:
   macro_using_local   ; like "ld hl,.local" inside macro
   ; will reach for my.local label from inside the macro
```
And this feature works also in nested way, and that's thanks to the design how the macro prefix is constructed, using unique id for every macro emission, and adding more nested id to the front of the current prefix, i.e. `2.1>val` for macro instance "2" inside macro instance "1" defining it's own `.val` label.

This will not help you, I'm more like documenting what I did find so far, so I don't forget it about next time I will take a look on this issue.

So the obvious solution, replacing unique instance id with the user defined label (in your case `Chunks.C00`) would work well for non-nested instances. Nesting makes this all more tricky, and mixing explicit/implicit macro ids...

I will have to create more examples for myself to be sure any new logic makes sense and works well (intuitively) in all the cases.

-------------------------

There is one not so pretty workaround available for you right now, which may cover your needs (with a bit of luck).

If you need these labels defined inside macros always for that particular macro, you can instead of local label define global one, and use macro argument to specify it's full name, for example like this:

```
 MACRO Example1 label_prefix?
label_prefix?_val EQU $+1
  ld a,0 : ld (hl),a : inc h : ret
 ENDM
 MACRO Example2 label_prefix?
  ld a,(de) : ld (hl),a : inc h : ret
label_prefix?_val EQU $+1
  ld a,0 : ld (hl),a : inc h : ret
 ENDM
 ALIGN 256
Chunks:
 ORG Chunks+15*0
 Example1 Chunks.C00
 ORG Chunks+15*1
 Example2 Chunks.C01

 ld a,#05 : ld (Chunks.C00_val),a
 ld a,#07 : ld (Chunks.C01_val),a
```
The usage of `_` in `label_prefix?_val` is important, it will make the macro-argument substitution to consider sub-word for replacement (`label_prefix?.val` will be not replaced with argument value). The argument must be non-local label, otherwise the macro instance id will be used as prefix.

But this is maybe more limited, probably difficult/impossible to use in nested way.

I like this idea of specifying macro instance id explicitly in source, so I will keep looking into this, especially if I will finally refactor the whole label system for "v2.x", but probably don't hold your breath now, and check if the work-around is sufficient for you, because this may take long time to arrive...

**Comment by specke** [comment]
I am sorry it took me so long to get back to this. I understand your explanation about how the current mechanics of macro-instancing works and, in fact, I can see a possible problem with my suggestion if someone attempts things like
```
  MACRO Macro_Instance
.LocalLabel EQU $+1
  ld a,0 : ld (hl),a : inc hl
  ENDM
Label1:
  Macro_Instance
  Macro_Instance
```
what will `ld (Label1.LocalLabel)` do? So, yes, I get it, there needs to be some explicit convention about instancing and a mechanism to catch possible errors such as the shown above.

I was also very interested in the alternative solution that you proposed. I am not sure I like it just yet, but I definitely do not understand it fully, because I do not believe the use of _ to concatenate labels is described anywhere in the documentation. Could you please explain the use of this concatenation mechanism better? I.e. what are the assumptions, does it works in macros only or everywhere, are there any issues with the use of local labels outside of macros, etc etc.

The label concatenation mechanism in general is something that is missing in sjasmplus compared to many native assemblers. So I believe even a limited form of concatenation, such as you outlined before, can be very important in some situations.

**Comment by ped7g** [comment]
> because I do not believe the use of _ to concatenate labels is described anywhere in the documentation.

Yes, that's #37 ... which confused me initially a lot, to the point, that I even partially rewrote the substitution system few months later. But I'm still not happy with the final result. Although you can find in that issue description of current rules and status IIRC, I hope I documented it at least there.

The stages of assembling source line are something like this:

1) line is read (here the colon is detected and splits real source line into multiple sub-lines, so the "readLine" has to be capable to skip over strings to not detect colon inside string literals -> lot more complex code than how "readLine" may sound)

2) substitutions are done - these are like C preprocessor, replacing string with string. The substitutions can be defined by `DEFINE` or as macro-argument-name. (the substitutions are substituted until no-change is detected, or 20x limit is hit)

3) [assembler] parser looks for label (or directive starting at beginning of line, if --dirbol is enabled)
- label can be followed by `EQU`/`DEFL`/`=` or `MACRO`, all of them causing further parsing and appropriate reactions (starting macro definition, or evaluating value for label)

4) parser looks for dot repeater, or other directive, or macro

5) parser looks for instruction, and if instruction needs arguments, it will evaluate them

So in code like this:
```
m1  MACRO arg1?
lab1_arg1?   ld hl,lab2_arg1? :ret
    ENDM

    DEFINE lab1 mainLabel
    DEFINE lab2 secondLabel

    m1 value
lab2_value   DB  1
```
what happens... the macro `m1` is defined, then defines `lab1` and `lab2` are defined for substitution, then the macro `m1` is expanded with `arg1?` value being `value`, so the macro expansion emits first part of line (till colon):
`lab1_arg1?   ld hl,lab2_arg1?`

The substitution step will first look for macro-arguments with higher priority (IIRC), so it will find both `arg1?` after the underscores, and replace them with `value`:
`lab1_value   ld hl,lab2_value`

Then the substitution does find and replace the `lab1` and `lab2` defines:
`mainLabel_value   ld hl,secondLabel_value`

And the subtitution phase is finished, and the string above is assembled as asm source, defining the new main label `mainLabel_value` and instruction `ld hl,...` using the address of `secondLabel_value` as value.

Then the second part of macro-definition line, the one after colon, is emitted, with fake space ahead (the sub-parts of line after colon can't define label in sjasmplus, so there's always extra space added ahead to prevent the `ret` becoming label:
` ret`

There's nothing to substitute there, and the assembler will just find ret instruction and produce machine code of it.

Then the final line of source is processed (substituted first):
`lab2_value   DB  1`

The `lab2` will be found by substitution and replaced:
`secondLabel_value   DB  1`

And this is then assembled, so the label `secondLabel_value` is defined, and byte with value 1 is emitted.

The underscore works as word-boundary delimiter for the substitution looking for string to be replaced (but define starting with underscore are disabled for sub-word substitution).

The initial patch adding this sub-word substitution into sjasmplus was actually meant the opposite way, only defines starting with underscore should have been considered for sub-string substitution, but the bug in the original implementation, and the wrong test (testing the incorrect behaviour) made me "fix" the implementation the incorrect way... :) .. I did realize only some days/weeks afterward what was the original idea of the author, and how the implementation was originally bugged in different way than I thought, but at that point I decided to keep my version of the moment.

**Comment by ped7g** [comment]
The original sjasm in version 0.42 has syntax for this (defining non-macro local labels): http://www.xl2s.tk/sjasmman11.html#s8

> When you define a local label inside a macro, the label will be local to the macro, each time it is expanded. You must use @ to escape from this behavior, if desirable

So `@.val EQU $+1` can be used in sjasm to define labels like `Chunks.C00.val` from inside macro.

And after v1.18.3 release this will be part of sjasmplus syntax too (or build from master branch right now :) )...

See [local_labels.lst test](../blob/master/tests/macros/local_labels.lst) for example of the syntax + outcome
