### ISSUE TITLE
Space allocation

### ISSUE THREAD

**Issue by ammehet** [z00m128/sjasmplus#88]
This sample code produces 14-byte binary:

```
    device zxspectrum48

    org 0x6000
start
    ld hl,Pixbytes
    ld de,Pixbytes+1
    ld bc, Attrbytes-Pixbytes
    ld (hl),0
    ldir
    ret

    align 256
Pixbytes
    defs 6144
Attrbytes
    defs 768
THE_CASE
    defb 0
    defs 4096

    savetap "test.tap",start
```

When I change ```defb 0``` to ```defb <something_not_0>``` at THE_CASE label, I have 7K binary as expected to initialize memory.

Is this behavior correct or something went wrong?

**Comment by ped7g** [comment]
The `ds 6144` *does* set the device memory to zero, so the definition of your data is OK.

But the `savetap` "snapshot" variant is trying to be smart and detect how big the CODE block should be, so it's going from the end of memory and skipping all zero bytes until it does reach some non-zero value.

You can get the zero bytes into the TAP by adding some non-zero marker after your last byte, like in your example by adding `db 0xAA` just ahead of the `savetap`.

I guess the behaviour is meant as "feature", but if you have zero-filled buffers at the end of your memory and you expect them to be initialized (instead of clearing them by code), then the `savetap` "snapshot" will ruin it for you.

Overall the "snapshot"-variant of `savetap` is in the circle of sjasmplus current contributors (me, busy, z00m, mborik, ...) ignored (it's not covered by tests, I haven't reviewed the implementation and we don't use it in our projects), as we prefer to build the TAP file ourselves by specifying each tape data block fully, and the docs don't describe this "feature" of shortening the file as much as possible, so I will "fix" this bug by adding some sentence to docs about it trying to be smart.

But overall this particular "tap snapshot" feature is sort of second-class citizen for current contributors, so proceed with caution (I guess if you would try to like really fill the device memory using also low regions, or ZX128 banks, the resulting TAP would be even more broken, missing the things outside of range which is covered by current implementation). The recommended way is to build the TAP file explicitly per each block (those variants are test-covered and docs are ... similarly sparse, oh well, but hopefully sufficient). Which may be slightly cumbersome as you need to provide BASIC loader, from what have I seen each of us has different approach, from defining it by `DB` statements manually to producing the binary/tap by zmakebas or bas2tap utilities and adding further blocks with sjasmplus (or incbin the loader) or even having loader-TAP file prepared from the regular ZX/emulator and copying that as start file for each assembling.

If you are OK with snapshot-nature of result, using `SAVESNA` is probably better choice, that is expected to work also in more complex cases, like using full zx48 RAM, etc...

**Comment by ammehet** [comment]
Thanks for the detailed explanation, now everything became clear. This should be reflected in the docs so that no more such misunderstanding arise.
