### ISSUE TITLE
Another case of local macros using.

### ISSUE THREAD

**Issue by luchibobra** [z00m128/sjasmplus#89]
I found that SjASMPlus can define local macros. But it's imposible to use this macro outside local space: 
```asm
label:
.m1     macro
        ; put some code here
        endm

       .m1 ; this macros works

label2:
       .m1 ; this doesn't (as expected)
       label.m1 ; also not works 
```

**Comment by ped7g** [comment]
The example works for me.. I mean the second `.m1 ; this doesn't (as expected)` actually works for me. The `label.m1` does not ("as expected" if you know the macros names are not labels... looking into docs, it's not explained, so I understand it is a bit secret)

Macro names are not subject to local label rules or modules, they always produce global name, literally as specified in source. So your macro has `.m1` name.

If the example fails for you, can you try to add new line `DB _VERSION` somewhere and do the:
`sjasmplus --lst --lstlab test.asm` and post the resulting listing file, so I can see how it fails and what version of sjasmplus was used? (I think some older ones may have modified the macro name as if it was local label, but I can't remember in which version I was fixing something about macro names).

**Comment by luchibobra** [comment]
Oh, i actualy did not tested posted example, but i was sure about result of this code. I tested it only after your answer and result was a surprise for me. Later i tested it on slightly modified work file, and instead of *unrecognized instruction* error there was a *label not found* (and i understand why this happen). So i even think this is not any sort of bug or feature but my negligence... My bad.

**Comment by ped7g** [comment]
well, `UNDEFINE` will not see macro name either, because it's neither in define space. Macros are extra (sort of like new instructions, but have higher priority in parsing)

The line processing goes sort of like this (I should really write some chapter about this in the documentation... or somebody else should):
source line -> defines are substituted -> label is detected/processed -> macros are detected/processed -> directive+instruction is processed.

With the exception (just found it now thanks to your report) of `--dirbol` when there's extra "directives detect+process" step ahead of label processing (so with `--dirbol` you can for certain directives to process ahead of macros if you put them at beginning of line, or after macros when they are in middle of line ... imagine defining macro `db` or `include` ... if you want to confuse readers of your source code completely... hehe)

What you probably can use as workaround (to have "local" macros) is to define macros with some distinct global name like
```
module1.label1.m1 macro
  ; ...
  endm

module2.label3.m1 macro
  ; ...
  endm

  DEFINE .m1 module1.label1.m1

  .m1  ; normal code using macro ".m1"

  UNDEFINE .m1   ; done with that variant of ".m1" macro, now you need other
  DEFINE .m1 module2.label3.m1  ; switch to second variant

  .m1  ; in regular code
```

This should work.

**Comment by ped7g** [comment]
ups... trying it out myself, you can't define "`.m1`" for substitution, the pattern-word can't start with dot. so you would have to define some name like `m1` to be alias for the long-name macro.
