### ISSUE TITLE
FORG from z80asm, NOP generation

### ISSUE THREAD

**Issue by devinterx** [z00m128/sjasmplus#90]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.14.3 	| Win64 | FORG? |

Hi, I 'm writing a z80 processor emulation and when using your compiler ran into a problem:

Compared to the previous compiler, not working correctly with `FORG`
Is there any replacement in the SjASMPlus for this instruction?

Simple code for reproduce:
```asm
        OUTPUT  "ram.rom"
        DEVICE  ZXSPECTRUM48
;--------------------------------
        ORG	$0000
					     
        JP  START              
;--------------------------------
        ORG	$0066
        ;FORG 0x0066
					     
        JP  START 
;--------------------------------
        ORG	$0100
        ;FORG 0x0100
					    
START:	DI
        LD  a, 0x10
        LD  (0x4010), a
        
        LD  a, (0x4010)
        OUT (54H), a
        
        HALT
;--------------------------------
```
SjASMPlus output:
```
DUMP ROM:
0000 | c3 00 01 c3 00 01 f3 3e   33 32 10 40 3e 39 32 11   
0010 | 40 3e 4b 32 12 40 3a 10   40 d3 54 3a 11 40 d3 54   
0020 | 3a 12 40 d3 54 76 00 00   00 00 00 00 00 00 00 00   
0030 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0040 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0050 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0060 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0070 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00  
```
z80asm output, with `FORG`:
```
DUMP ROM:
0000 | c3 00 01 00 00 00 00 00   00 00 00 00 00 00 00 00   
0010 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0020 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0030 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0040 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0050 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0060 | 00 00 00 00 00 00 c3 00   01 00 00 00 00 00 00 00   
0070 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0080 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0090 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
00A0 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
00B0 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
00C0 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
00D0 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
00E0 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
00F0 | 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   
0100 | f3 3e 10 32 10 40 3a 10   40 d3 54 76 00 00 00 00  
```

**Comment by ped7g** [comment]
Yes, I can think of two basic options/ways:

1) as you are using virtual device ZXSPECTRUM48, it has the initial 64kiB block of memory mostly zeroed (except screen being "CLS", fake sysvars and fake stack toward end of the memory ... if you want to be sure the whole device is zeroed, you can do `device ZXSPECTRUM48 : org 0 : block $10000,0`). So your current code does look in the device memory as what you want, but the `output` way of getting binary is like "stream" output of emitted bytes. So instead of `output "ram.rom"` you can get the memory dump with `savebin "ram.rom", $0000, $` after the last instruction (so the `$` works as length, or you can put some wanted length explicitly) - but make sure the `savebin` is done at the moment when the device memory contains what you want to save, as you can use multiple `savebin` commands, modifying the device memory to different state, so compared to `output` which is opened ahead, `savebin` is "dump" of current state at the line where it is used.

The major difference from stream-approach is, that you can be more relaxed about the order in which you set up the device memory in the source, you can first define some code at $c000, then fill up data at $2000, etc... and then you can dump the rom image when you are done, while in the stream-like source you must emit all bytes in correct order, so the flow of the source must follow the flow of the output ... but generally both ways seems to me usable, so it's down to personal preference.

Another thing the device-approach has extra is the actual memory model for larger devices like ZX128 or ZX Next, where you can "map" the memory as at runtime, and that will make the code labels defined in particular page to have that information, which may be handy when writing the bank-switching code or just when you are dumping the memory per particular page (`savebin/savedev`), or when you are using emulator capable to process export of labels with page info, to make debugging in emulator more convenient.

And final extra feature of `device` is the ability to read the value in memory in third pass of assembling by `{ address }` to read the word value (`{b address}` to read byte), which can be used by macros for example to calculate checksums of some block of memory, etc. (it's a bit limited in usage as it returns zero in first and second pass, so it can't be used for conditional `IF` to emit/skip part of code, that would not work, but things just calculating some value like checksum or xor-encrypt work well)

2) instead of `FORG` use `BLOCK` fill, actually the `ORG` docs have example of macro `PADORG2` which is IMO replacement for `FORG`: http://z00m128.github.io/sjasmplus/documentation.html#po_org
You can copy that, and just rename it to `FORG` and use it same way as in z80asm.

**Comment by ped7g** [comment]
And your example modified to use that macro as `FORG` replacement:
 [tests/devices/extra/Issue90_FORG_replacement.asm](https://github.com/z00m128/sjasmplus/blob/master/tests/devices/extra/Issue90_FORG_replacement.asm)
(I also did add `SIZE` to pad total output to 320 bytes, that's just me testing if everything works as expected, remove that in your code if you want length of output as is at the end of the source code)
