### ISSUE TITLE
Labels inside list file not always end with ":"

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#91]
sjsamplus v1.13.3.

Hi,

I don't know if this is bug or if it was done intentionally. Then this might be  feature request.

For my vscode debug extension I'm parsing the list file to get all labels.
I'm looking for a name that ends with ":".
Normally I use labels with ending ":" in my source files and with those also the labels in the list file end with a ":"
But when I use a label without ending ":" the label in the list file will have no ":" as well.
Then my parser misses the label.

You can of course say my parser is dumb. But on the other hand:
Wouldn't it be better that the format of the list file is always the same no matter from what sources it has been created.

So here is my request:
Could you always end the labels inside the list file with a ":".

(And, I like the ":". It's easier to distinguish labels from something else. :-)  )

**Comment by maziac** [comment]
Forget about it.
Dumb request.
I will handle that in my parser.

**Comment by ped7g** [comment]
in current sjasmplus the `:` after label is not mandatory (kinda unfortunately, but that's how it is).
But labels must start at first column.
Instructions (macro-emit too) can't be at first column, directives can be on first column only when `--dirbol` option is used. And when `--dirbol` is used, then `end/END/.end/.END` are still labels at beginning of line, the `END` directive must have whitespace ahead even with `--dirbol`.
And there is new syntax for macro-definitions, where macro name is at the label position (i.e. `example MACRO arg1`), those are not labels either.

All the rules may initially/independently feel simple, but due to those various exceptions, extra options and combinations it may get a bit tricky. If you have any chance to parse the final labels table at bottom of listing (`--lstlab`), there are all labels in canonical form (including modules/main parts of labels, and labels defined by structures), with all that noise (macros, directives) filtered out = I would maybe focus on this one, also the symbol values are there evaluated, so you can maybe hint that further, what is the final value of particular symbol.

Thinking about it, the `DEFL` (has alias `=`) symbols are not in the symbol table IIRC, because those are some sort of "variable" symbols, so the listing lists only other labels, so that's another exception. Hmm...

BUT, there is new "SLD" (Source Level Debugging) export, created for CKirby's debugger, it's kinda toward bigger size of files because it exports info about every instruction emitted, but actually I would love if you would take a look and check if this can be supported by your tools as well, that export is literally focused on debug tools and machine parsing (even for the price of some redundancy and bloat), but ultimately can allow even debugger UI showing for each instruction the source where it was emitted and if it was in macro, then even show definition of the Z80 instruction across multiple source files.
http://z00m128.github.io/sjasmplus/documentation.html#c_sld_data

If you have some ideas what is missing in the new format, and how to improve it, I'm surely open to ideas (seems CKirby unfortunately got really buried in work lately and the progress on his debugger seems a bit stalled).

**Comment by maziac** [comment]
Test SLD format sounds interesting. I will have a look when I have time.
(First I need to get the reverse debugging feature ready.)
