### ISSUE TITLE
String support on STRUCTs

### ISSUE THREAD

**Issue by sdsnatcher** [z00m128/sjasmplus#93]
Nowadays, the db/BYTE keywords in structures only support a single byte, unlike their equivalents outside structures.

But it would be very useful to have string (multibyte db) support on STRUCTs too. 

Some issues are:

- The field separator would probably have to be changed from comma to semicolon, because strings already use commas for that
- Multiline support would be a must

```
 STRUCT SCOLOR 
RED	db 4
GREEN	db 5
BLUE	db 6
TEXT1	ds	10,' '
TEXT2	ds	20,0
TEXT3	db	"default text",$0d,$0a
 ENDS

MYCOLOR1	 SCOLOR
MYCOLOR2	 SCOLOR 1;2;3
MYCOLOR3	 SCOLOR 1;2;3;"bla1";"bla2";"bla3"
MYCOLOR4	 SCOLOR 7;8;9;\
			"my long text1";\
			"my long text2",$0d,$0a;\
			"my long text3",$0

```
or maybe better, parenthesis (or some other similar delimiter) could be used for multi-line support instead of \\:

```
MYCOLOR4	 SCOLOR ( 7;8;9
			"my long text1";
			"my long text2",$0d,$0a;
			"my long text3",$0 )

```

**Comment by ped7g** [comment]
Commas are not an issue, if it would be new type of field, like array/text, the current curly braces syntax can be reused easily:
```
    struct XYZ
x     db      0
y     text    20, "default text", 13, 10
              ;20 is size, rest is default text
z     db      0
    ends

; instancing
inst  XYZ { 12, { "other", 13, 10, "text" }, 34 } ; x=12, z=34, y="other\r\ntext"
```

That's the easy part (probably doable also for current v1.x).

The multi-line `\` support is difficult part, can't see how to do it without rewriting the parser, and that's not going to happen for current v1.x, because it would probably break some old syntax/sources, and it's lot of work to do it well, so this is clearly v2.x candidate.

And while reading docs about structures, the structuring of init values by `{}` is not promoted enough, I did think it's more prominent in examples, but the tests confused me. Anyway, if you are more curious about *current* status of structure, it may help to read through the structure tests in https://github.com/z00m128/sjasmplus/tree/master/tests/struct

**Comment by sdsnatcher** [comment]
I'm fine with the curly braces.    :)

As long as the curly braces syntax support multi-line between { and }, it's enough. There will be no need for the multi-line \\ support.
